// Opt-in real-model recovery after an explicitly injected invalid evidence reference.
// Executes current Native read/interpretation tools against isolated real State.
import assert from "node:assert/strict";
import { parseArgs } from "node:util";
import { mkdtemp, readFile, writeFile, copyFile, rm, mkdir } from "node:fs/promises";
import { resolve, join } from "node:path";
import { pathToFileURL } from "node:url";
import { validateToolArguments } from "@earendil-works/pi-ai";
import { create_workspace_initializer } from "../../packages/agent-core/workspace.mjs";
import { create_python_kernel_bridge } from "../../packages/research-state-bridge/python_kernel_bridge.mjs";
import { createStateTool, createResearchLifecycleTool } from "../../apps/app-server/pi-native-tools.mjs";
import { createPublicToolAliases } from "../../packages/agent-runtime/host-api/tools.mjs";
import { createDecisionContextInjector } from "../../apps/app-server/decision-context.mjs";

const { values } = parseArgs({ options: { "agent-dir": { type: "string" }, output: { type: "string" }, runs: { type: "string", default: "2" } } });
const testRoot = resolve(process.env.TSPI_TEST_ROOT || "/home/iaw/debug/tspi-test-env");
const piRoot = process.env.TSPI_TEST_PI_RUNTIME_ROOT;
if (!piRoot || !values["agent-dir"] || !values.output) throw new Error("Supply pinned Pi, --agent-dir and --output");
const output = resolve(values.output);
if (!output.startsWith(testRoot + "/")) throw new Error("Output must be under TSPI_TEST_ROOT");
const runs = Number(values.runs);
if (!Number.isInteger(runs) || runs < 1 || runs > 3) throw new Error("runs must be 1..3");
const temporary = await mkdtemp(join(testRoot, "eval-recovery-"));
const previousWrites = process.env.TSPI_NATIVE_WRITES;
process.env.TSPI_NATIVE_WRITES = "1";
const record = { schema_version: "t003-live-recovery/1", runs: [], ok: false,
  limitations: "The initial Attempt-as-Artifact mistake is injected, not generated by the model. Bounded synthetic local jobs; this measures recovery, not spontaneous error frequency or full research performance." };
try {
  for (const file of ["models.json", "auth.json", "settings.json"]) await copyFile(join(values["agent-dir"], file), join(temporary, file));
  const settings = JSON.parse(await readFile(join(temporary, "settings.json"), "utf8"));
  const { ModelRuntime } = await import(pathToFileURL(join(piRoot, "packages/coding-agent/src/core/model-runtime.ts")));
  const runtime = await ModelRuntime.create({ modelsPath: join(temporary, "models.json"), authPath: join(temporary, "auth.json"),
    modelsStorePath: join(temporary, "models-store.json"), allowModelNetwork: false });
  const model = runtime.getModel(settings.defaultProvider, settings.defaultModel);
  if (!model) throw new Error("Configured model unavailable");
  record.model = { provider: model.provider, id: model.id };
  for (let run = 0; run < runs; run++) {
    const root = join(temporary, `workspace-${run}`);
    const initializer = create_workspace_initializer();
    await initializer.initialize_workspace({ workspace_root: root, workspace_id: `recovery_${run}`, workspace_mode: "research" });
    await initializer.admit_workspace(root);
    const bridge = create_python_kernel_bridge({ workspace_root: root });
    const row = { run, injected_error: true, turns: [], passed: false };
    record.runs.push(row);
    let job;
    try {
      await bridge.apply_change({ principal: "root_agent", authority: "kernel_write", operations: [
        { type: "create_claim", id: "claim_fixture", statement: "A synthetic process prints the literal marker evidence." },
        { type: "create_node", id: "node_fixture", title: "Marker", objective: "Observe process output", claim_ids: ["claim_fixture"], completion_exemption: "Synthetic execution fixture" },
        { type: "set_focus", claim_ids: ["claim_fixture"], node_ids: ["node_fixture"] },
        { type: "create_strategy_plan", id: "strategy_fixture", claim_id: "claim_fixture", node_id: "node_fixture", objective: "Read output", rationale: "Check marker", status: "active" },
      ] });
      job = await bridge.execute_command("job.start", { job_id: `job_recovery_${run}`, node_id: "node_fixture", command: [process.env.TSPI_PYTHON, "-c", "print('evidence')"], timeout_seconds: 5 });
      let status;
      for (let poll = 0; poll < 100; poll++) {
        status = await bridge.execute_command("job.status", { job_id: job.job_id });
        if (["succeeded", "failed", "timed_out"].includes(status.state)) break;
        await new Promise(resolve => setTimeout(resolve, 50));
      }
      assert.equal(status.state, "succeeded");
      const collected = await bridge.execute_command("job.collect", { job_id: job.job_id });
      const receipt = collected.result_receipt;
      const toolContext = { cwd: root, principal: "root_agent" };
      const tools = [createStateTool(), ...createPublicToolAliases([createResearchLifecycleTool()]).filter(tool => tool.name === "research_interpretation")];
      const execute = async call => {
        const tool = tools.find(tool => tool.name === call.name);
        if (!tool) throw new Error("Unsupported recovery tool");
        const args = validateToolArguments(tool, call);
        return tool.execute(call.id, args, undefined, toolContext, undefined, { abortSignal: AbortSignal.timeout(30_000) });
      };
      const invalid = { type: "toolCall", id: "call_injected", name: "research_interpretation", arguments: { interpretation: {
        id: "interpretation_fixture", claim_id: "claim_fixture", node_id: "node_fixture", attempt_ref: job.attempt_id,
        kind: "result", summary: "Synthetic process exited successfully", outcome: "inconclusive",
        result_receipt_ref: receipt.receipt_id, direct_evidence_refs: [job.attempt_id],
      } } };
      const before = await bridge.read_context();
      let rejection;
      try { await execute(invalid); } catch (error) { rejection = error.message; }
      assert.match(rejection || "", /evidence_reference_type_mismatch/);
      assert.deepEqual(await bridge.read_context(), before);
      row.rejection = rejection;
      row.rejected_write_unchanged = true;
      const messages = [
        { role: "user", content: "Record an inconclusive interpretation of the collected synthetic process result. Recover from the rejected write using the available tools. Keep the same interpretation ID and receipt; discover exact evidence IDs before retrying.", timestamp: Date.now() },
        { role: "assistant", content: [invalid], api: model.api, provider: model.provider, model: model.id, stopReason: "toolUse", timestamp: Date.now(),
          usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } } },
        { role: "toolResult", toolCallId: invalid.id, toolName: invalid.name, isError: true, content: [{ type: "text", text: rejection }], timestamp: Date.now() },
      ];
      const inject = createDecisionContextInjector({ sessionId: "recovery", readModel: async () => model, bridge,
        coordinator: { commit_files: async () => {} } });
      let queried = false;
      for (let turn = 0; turn < 5; turn++) {
        const request = await inject({ messages }, `recovery_${run}_${turn}`, "recovery");
        const response = await runtime.completeSimple(model, { systemPrompt: "Use current Research State and exact tool-returned identities. A rejected write is not persisted. Recover by reading evidence, then submit a valid interpretation. Do not invent IDs or claim scientific completion.", messages: request.messages, tools },
          { maxTokens: 1600, reasoning: "minimal", signal: AbortSignal.timeout(90_000) });
        messages.push(response);
        const entry = { content: response.content, usage: response.usage, stop_reason: response.stopReason, results: [] };
        row.turns.push(entry);
        const calls = response.content.filter(part => part.type === "toolCall");
        if (!calls.length) break;
        for (const call of calls) {
          let result, isError = false;
          try {
            result = await execute(call);
            if (call.name === "research_read" && call.arguments.mode === "evidence" && call.arguments.attempt_id === job.attempt_id) queried = true;
          } catch (error) { result = { error: error.message }; isError = true; }
          entry.results.push({ id: call.id, isError, result });
          messages.push({ role: "toolResult", toolCallId: call.id, toolName: call.name, content: [{ type: "text", text: JSON.stringify(result) }], isError, timestamp: Date.now() });
        }
        const state = await bridge.read_context();
        const interpretation = state.attempt_interpretations.find(item => item.id === "interpretation_fixture");
        if (interpretation) {
          row.final_interpretation = interpretation;
          row.queried_exact_attempt = queried;
          row.passed = queried && interpretation.direct_evidence_refs.length > 0 &&
            interpretation.direct_evidence_refs.every(id => receipt.artifact_refs.includes(id)) &&
            interpretation.attempt_ref === job.attempt_id && interpretation.result_receipt_ref === receipt.receipt_id;
          break;
        }
      }
    } finally {
      if (job?.job_id) await bridge.execute_command("job.cancel", { job_id: job.job_id }).catch(() => {});
      await bridge.close();
    }
    console.log(`recovery ${run + 1}: ${row.passed ? "pass" : "fail"}`);
  }
  record.ok = record.runs.length === runs && record.runs.every(run => run.passed);
} catch (error) { record.error = error.message; }
finally {
  if (previousWrites === undefined) delete process.env.TSPI_NATIVE_WRITES; else process.env.TSPI_NATIVE_WRITES = previousWrites;
  await mkdir(resolve(output, ".."), { recursive: true });
  await writeFile(output, JSON.stringify(record, null, 2) + "\n");
  await rm(temporary, { recursive: true, force: true });
}
if (!record.ok) process.exitCode = 1;
