from __future__ import annotations

import json
import subprocess
from pathlib import Path

from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[1]
SYNC = ROOT / "tools" / "contracts" / "sync_ts_phone.py"


def test_vendored_phone_protocol_fixture_is_self_consistent() -> None:
    completed = subprocess.run(
        ["python3", str(SYNC), "--check"], cwd=ROOT, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
    )
    assert completed.returncode == 0, completed.stderr
    versions = json.loads((ROOT / "contracts/ts-phone/versions.json").read_text(encoding="utf-8"))
    manifest = json.loads((ROOT / "contracts/ts-phone/manifest.json").read_text(encoding="utf-8"))
    assert manifest["protocols"] == {
        "api": versions["api"], "events": versions["events"], "bridge": versions["bridge"],
    }
    assert "Generated by tools/contracts/sync_ts_phone.py" in (
        ROOT / "extensions/ts-phone-bridge/protocol.ts"
    ).read_text(encoding="utf-8")


def test_phone_fixture_matches_the_canonical_checkout_when_available() -> None:
    canonical = Path("/home/iaw/Codex/Project/2026-08-14/ts-phone/packages/protocol")
    if not canonical.is_dir():
        return
    completed = subprocess.run(
        ["python3", str(SYNC), "--check", "--source", str(canonical)], cwd=ROOT,
        text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
    )
    assert completed.returncode == 0, completed.stderr


def test_web_snapshot_fixture_matches_its_public_contract() -> None:
    schema = json.loads((ROOT / "contracts/ts-web/workspace-snapshot.schema.json").read_text(encoding="utf-8"))
    fixture = json.loads((ROOT / "contracts/ts-web/workspace-snapshot.fixture.json").read_text(encoding="utf-8"))
    errors = list(Draft202012Validator(schema).iter_errors(fixture))
    assert errors == []
    assert "source_root" not in json.dumps(fixture)
