import { SLASH_COMMAND_NAMES } from "../packages/ts-agent-runtime/host-api/commands.mjs";

export const TS_PACKAGE_PROFILE = Object.freeze({
  displayName: "TSPi",
  version: "0.17.0",
  title: "TSPi research workspace",
  description: "ResearchMap-driven transition-state research with explicit scientific workflows and deterministic execution.",
  skills: Object.freeze([
    Object.freeze({ name: "tspi-research-kernel", path: "./skills/tspi-research-kernel" }),
    Object.freeze({ name: "tspi-orchestration", path: "./skills/tspi-orchestration" }),
    Object.freeze({ name: "tspi-ts-candidate-generation", path: "./skills/tspi-ts-candidate-generation" }),
    Object.freeze({ name: "tspi-ts-validation", path: "./skills/tspi-ts-validation" }),
    Object.freeze({ name: "tspi-irc", path: "./skills/tspi-irc" }),
    Object.freeze({ name: "tspi-energetics", path: "./skills/tspi-energetics" }),
    Object.freeze({ name: "tspi-method-selection", path: "./skills/tspi-method-selection" }),
    Object.freeze({ name: "cf22d", path: "./skills/cf22d" }),
    Object.freeze({ name: "tspi-xtb", path: "./skills/tspi-xtb" }),
    Object.freeze({ name: "tspi-crest", path: "./skills/tspi-crest" }),
    Object.freeze({ name: "tspi-qbics", path: "./skills/tspi-qbics" }),
    Object.freeze({ name: "tspi-gaussian", path: "./skills/tspi-gaussian" }),
    Object.freeze({ name: "tspi-report", path: "./skills/tspi-report" }),
    Object.freeze({ name: "tspi-render", path: "./skills/tspi-render" }),
    Object.freeze({ name: "tspi-email", path: "./skills/tspi-email" }),
    Object.freeze({ name: "tspi-mechanism-reasoning", path: "./skills/tspi-mechanism-reasoning" }),
    Object.freeze({ name: "tspi-chemical-input", path: "./skills/tspi-chemical-input" }),
  ]),
  extensions: Object.freeze([
    Object.freeze({ name: "research", path: "./extensions/pi/research/index.ts" }),
    Object.freeze({ name: "ui", path: "./extensions/pi/ui/index.ts" }),
    Object.freeze({ name: "review", path: "./extensions/pi/review/index.ts" }),
    Object.freeze({ name: "compute", path: "./extensions/pi/compute/index.ts" }),
    Object.freeze({ name: "artifacts", path: "./extensions/pi/artifacts/index.ts" }),
  ]),
  theme: Object.freeze({ name: "ts-theme", path: "./themes/ts-theme.json" }),
  commands: SLASH_COMMAND_NAMES,
});
