"""Canonical research-map domain model and kernel boundary."""

from .model import (
    ClaimStatus,
    ContinuationAction,
    ContinuationRecord,
    ContinuationScope,
    ContinuationStatus,
    FactFinding,
    Finding,
    FindingKind,
    FindingStatus,
    Gate,
    GateEvaluation,
    GateScope,
    GateVerdict,
    IssueFinding,
    NodeOutcome,
    NodeState,
    ResearchClaim,
    ResearchMap,
    ResearchModelError,
    ResearchNode,
    ResearchObject,
    ResearchPhase,
    ClaimGate,
    NodeGate,
)
from .kernel import ResearchKernel, ResearchKernelError

__all__ = [
    "ClaimGate",
    "ClaimStatus",
    "ContinuationAction",
    "ContinuationRecord",
    "ContinuationScope",
    "ContinuationStatus",
    "FactFinding",
    "Finding",
    "FindingKind",
    "FindingStatus",
    "Gate",
    "GateEvaluation",
    "GateScope",
    "GateVerdict",
    "IssueFinding",
    "NodeGate",
    "NodeOutcome",
    "NodeState",
    "ResearchClaim",
    "ResearchKernel",
    "ResearchKernelError",
    "ResearchMap",
    "ResearchModelError",
    "ResearchNode",
    "ResearchObject",
    "ResearchPhase",
]
