"""Canonical research-map domain model and kernel boundary."""

from .model import (
    ClaimStatus,
    ContinuationAction,
    ContinuationRecord,
    ContinuationScope,
    ContinuationStatus,
    FactFinding,
    Finding,
    FindingKind,
    FindingStatus,
    Gate,
    GateEvaluation,
    GateScope,
    GateVerdict,
    IssueFinding,
    NodeOutcome,
    NodeState,
    ResearchClaim,
    ResearchMap,
    ResearchModelError,
    ResearchNode,
    ResearchObject,
    ResearchPhase,
    ClaimGate,
    NodeGate,
)
from .decisions import (
    AttemptInterpretation,
    DecisionModelError,
    InterpretationOutcome,
    StrategyPlan,
    StrategyReview,
    StrategyReviewDecision,
    StrategyStatus,
    TurnCheckpoint,
    TurnDisposition,
)
from .evidence import ArtifactManifest, AttemptRecord, EvidenceLink, EvidenceModelError
from .kernel import ResearchKernel, ResearchKernelError
from .sqlite import ResearchSqliteError, ResearchSqliteRepository

__all__ = [
    "ClaimGate",
    "AttemptInterpretation",
    "AttemptRecord",
    "ArtifactManifest",
    "ClaimStatus",
    "ContinuationAction",
    "ContinuationRecord",
    "ContinuationScope",
    "ContinuationStatus",
    "DecisionModelError",
    "EvidenceLink",
    "EvidenceModelError",
    "FactFinding",
    "Finding",
    "FindingKind",
    "FindingStatus",
    "Gate",
    "GateEvaluation",
    "GateScope",
    "GateVerdict",
    "IssueFinding",
    "InterpretationOutcome",
    "NodeGate",
    "NodeOutcome",
    "NodeState",
    "ResearchClaim",
    "ResearchKernel",
    "ResearchKernelError",
    "ResearchMap",
    "ResearchModelError",
    "ResearchNode",
    "ResearchObject",
    "ResearchPhase",
    "ResearchSqliteError",
    "ResearchSqliteRepository",
    "StrategyPlan",
    "StrategyReview",
    "StrategyReviewDecision",
    "StrategyStatus",
    "TurnCheckpoint",
    "TurnDisposition",
]
