"""Scheduler backend protocol for future Slurm or LSF support."""

from __future__ import annotations

from typing import Any, Protocol

from ..models import JobSubmission


class SchedulerBackend(Protocol):
    def list_queues(self) -> list[dict[str, Any]]: ...

    def list_nodes(self) -> list[dict[str, Any]]: ...

    def list_jobs(self, owner: str) -> list[dict[str, Any]]: ...

    def get_job(self, job_id: str, *, include_history: bool = False) -> dict[str, Any]: ...

    def validate_submission(self, submission: JobSubmission) -> None: ...

    def submit(self, submission: JobSubmission) -> dict[str, Any]: ...

    def hold(self, job_id: str) -> dict[str, Any]: ...

    def release(self, job_id: str) -> dict[str, Any]: ...

    def alter_walltime(self, job_id: str, walltime: str) -> dict[str, Any]: ...

    def delete(self, job_id: str) -> dict[str, Any]: ...

    def health_check(self) -> dict[str, Any]: ...
