// Generated by scripts/update_tool_types.mjs. Do not edit independently.
export interface ToolParameters {
  systemPrompt: Record<string, never>;
  state: {
    "root"?: string;
    "query"?: string;
    "source_ref"?: string;
    "claim_id"?: string;
    "record_type"?: string;
    "node_id"?: string;
    "artifact_id"?: string;
    "attempt_id"?: string;
    "job_id"?: string;
    "offset"?: number;
    "max_bytes"?: number;
    "event_ids"?: Array<string>;
    "subject_id"?: string;
    "limit"?: number;
    "kind"?: string;
    "id"?: string;
    "mode"?: "map" | "summary" | "context" | "liveness" | "detail" | "locate" | "validate" | "operations" | "decisions" | "evidence" | "storage" | "requirements" | "profiles" | "sources";
  };
  change: {
    "rationale": string;
    "operations": Array<{
      "type": "create_phase";
      "id": string;
      "title": string;
      "objective"?: string;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
    } | {
      "type": "create_claim";
      "id": string;
      "statement": string;
      "status"?: "proposed";
      "source_refs"?: Array<string>;
      "constraints"?: Array<string>;
      "predictions"?: Array<string>;
      "falsifiers"?: Array<string>;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
    } | {
      "type": "assess_claim";
      "id": string;
      "claim_id": string;
      "verdict": "proposed" | "supported" | "contradicted" | "inconclusive" | "withdrawn";
      "reason": string;
      "evidence_refs"?: Array<string>;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
      "actor"?: Record<string, unknown>;
    } | {
      "type": "revise_claim";
      "revision_id": string;
      "source_claim_id": string;
      "target_claim_id": string;
      "statement": string;
      "reason": string;
      "relation"?: "revises" | "refines" | "supersedes";
      "predictions"?: Array<string>;
      "falsifiers"?: Array<string>;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
      "actor"?: Record<string, unknown>;
    } | {
      "type": "create_node";
      "id": string;
      "title": string;
      "objective": string;
      "phase_id"?: string;
      "claim_ids"?: Array<string>;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
      "dependencies"?: Array<{
        "node_id": string;
        "condition": "completed" | "finished";
      }>;
      "consumes"?: {
        "requirement_ids"?: Array<string>;
        "artifact_refs"?: Array<string>;
        "condition"?: "satisfied" | "observed";
      };
    } | {
      "type": "create_finding";
      "id": string;
      "node_id": string;
      "statement": string;
      "kind": "fact" | "issue";
      "claim_ids"?: Array<string>;
      "source_refs"?: Array<string>;
      "value"?: unknown;
      "datatype"?: string;
      "unit"?: string;
      "provenance"?: Record<string, unknown>;
      "status"?: "open" | "confirmed" | "resolved" | "accepted" | "superseded";
      "severity"?: string;
      "resolution"?: string;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
    } | {
      "type": "resolve_issue";
      "id": string;
      "resolution": string;
      "source_refs"?: Array<string>;
    } | {
      "type": "create_gate";
      "id": string;
      "scope": "node" | "claim";
      "target_id": string;
      "criteria": Array<{
        "id": string;
        "source_type": "agent_assessment" | "runtime_fact" | "validator_result";
        "description"?: string;
        "fact"?: "execution_succeeded" | "outputs_collected" | "artifacts_registered";
        "validator_id"?: string;
        "validator_version"?: string;
        "bindings"?: Record<string, string | number | boolean>;
      }>;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
    } | {
      "type": "set_lifecycle_action";
      "id": string;
      "scope": "node" | "claim" | "gate";
      "target_id": string;
      "action": "inspect" | "finalize" | "launch" | "analyze" | "review" | "evaluate" | "close";
      "status"?: "required" | "deferred" | "blocked" | "completed";
      "reason"?: string;
      "request_id"?: string;
      "created_at"?: string;
      "metadata"?: Record<string, unknown>;
    } | {
      "type": "resolve_lifecycle_action";
      "id": string;
      "status": "required" | "deferred" | "blocked" | "completed";
      "reason"?: string;
      "request_id"?: string;
    } | {
      "type": "revise_gate";
      "gate_id": string;
      "criteria": Array<{
        "id": string;
        "source_type": "agent_assessment" | "runtime_fact" | "validator_result";
        "description"?: string;
        "fact"?: "execution_succeeded" | "outputs_collected" | "artifacts_registered";
        "validator_id"?: string;
        "validator_version"?: string;
        "bindings"?: Record<string, string | number | boolean>;
      }>;
      "reason": string;
    } | {
      "type": "evaluate_gate";
      "gate_id": string;
      "assessments": Array<{
        "criterion_id": string;
        "verdict"?: "pass" | "fail" | "inconclusive" | "blocked";
        "reason"?: string;
        "result_receipt_ref"?: string;
      }>;
      "verdict": "pass" | "fail" | "inconclusive" | "blocked";
      "message"?: string;
      "evidence_refs"?: Array<string>;
      "created_at"?: string;
    } | {
      "type": "set_node_state";
      "node_id": string;
      "state": "planned" | "active" | "paused" | "blocked" | "closed";
      "outcome"?: "completed" | "inconclusive" | "stopped";
      "summary"?: string;
    } | {
      "type": "set_claim_status";
      "claim_id": string;
      "status": "proposed" | "withdrawn";
    } | {
      "type": "relate_claims";
      "source_id": string;
      "target_id": string;
      "relation": string;
    } | {
      "type": "set_focus";
      "claim_ids": Array<string>;
      "node_ids": Array<string>;
    } | {
      "type": "review_source";
      "source_ref": string;
      "reason": string;
      "disposition": "requirements_recorded" | "no_new_requirements";
      "requirement_ids"?: Array<string>;
    } | {
      "type": "create_requirement";
      "id": string;
      "source_ref": string;
      "source_quote": string;
      "statement": string;
      "acceptance_profile"?: {
        "id": string;
        "version": string;
      };
      "constraints"?: Record<string, string | number | boolean>;
      "input_artifact_ids"?: Array<string>;
      "node_ids"?: Array<string>;
      "criteria"?: Array<{
        "id": string;
        "source_type": "agent_assessment" | "runtime_fact" | "validator_result";
        "description"?: string;
        "fact"?: "execution_succeeded" | "outputs_collected" | "artifacts_registered";
        "validator_id"?: string;
        "validator_version"?: string;
        "bindings"?: Record<string, string | number | boolean>;
      }>;
      "execution_required"?: boolean;
    } | {
      "type": "bind_requirement";
      "requirement_id": string;
      "reason": string;
      "node_ids"?: Array<string>;
      "input_artifact_ids"?: Array<string>;
    } | {
      "type": "revise_requirement";
      "requirement_id": string;
      "reason": string;
      "constraints"?: Record<string, string | number | boolean>;
      "criteria"?: Array<{
        "id": string;
        "source_type": "agent_assessment" | "runtime_fact" | "validator_result";
        "description"?: string;
        "fact"?: "execution_succeeded" | "outputs_collected" | "artifacts_registered";
        "validator_id"?: string;
        "validator_version"?: string;
        "bindings"?: Record<string, string | number | boolean>;
      }>;
      "execution_required"?: boolean;
      "acceptance_profile"?: {
        "id": string;
        "version": string;
      };
    } | {
      "type": "assess_requirement";
      "id": string;
      "requirement_id": string;
      "reason": string;
      "evidence_refs"?: Array<string>;
      "result_receipt_refs"?: Array<string>;
      "assessments"?: Array<{
        "criterion_id": string;
        "verdict"?: "pass" | "fail" | "inconclusive" | "blocked";
        "reason"?: string;
        "result_receipt_ref"?: string;
      }>;
    } | {
      "type": "record_requirement_stop";
      "id": string;
      "requirement_id": string;
      "reason": string;
      "category": "user_cancel" | "execution_failed" | "capability_unavailable";
      "source_ref"?: string;
      "source_quote"?: string;
      "evidence_refs"?: Array<string>;
      "result_receipt_refs"?: Array<string>;
    } | {
      "type": "resume_requirement";
      "requirement_id": string;
      "reason": string;
    } | {
      "id": string;
      "claim_id"?: string;
      "node_id"?: string;
      "objective": string;
      "rationale": string;
      "steps"?: Array<Record<string, unknown>>;
      "alternatives"?: Array<Record<string, unknown>>;
      "stop_conditions"?: Array<string>;
      "switch_conditions"?: Array<string>;
      "status"?: "proposed" | "active" | "superseded" | "completed" | "blocked";
      "type": "create_strategy_plan";
      "created_at"?: string;
      "actor"?: Record<string, unknown>;
      "metadata"?: Record<string, unknown>;
      "supersedes_id"?: string;
    } | {
      "id": string;
      "claim_id"?: string;
      "decision": "continue" | "switch" | "stop" | "blocked";
      "rationale": string;
      "selected_strategy_id"?: string;
      "trigger_refs"?: Array<string>;
      "attempt_refs"?: Array<string>;
      "type": "create_strategy_review";
      "created_at"?: string;
      "actor"?: Record<string, unknown>;
      "metadata"?: Record<string, unknown>;
      "previous_strategy_id"?: string;
      "alternatives_considered"?: Array<Record<string, unknown>>;
      "node_id"?: string;
    } | {
      "id": string;
      "claim_id"?: string;
      "node_id"?: string;
      "attempt_ref": string;
      "summary": string;
      "outcome": "supports" | "contradicts" | "inconclusive" | "invalid";
      "kind": "result" | "observation" | "execution_issue";
      "direct_evidence_refs"?: Array<string>;
      "comparison_evidence_refs"?: Array<string>;
      "background_evidence_refs"?: Array<string>;
      "result_receipt_ref"?: string;
      "execution_observation_ref"?: string;
      "supersedes_id"?: string;
      "finding_ids"?: Array<string>;
      "gate_ids"?: Array<string>;
      "type": "create_interpretation";
      "created_at"?: string;
      "actor"?: Record<string, unknown>;
      "metadata"?: Record<string, unknown>;
    }>;
    "basis_refs"?: Array<string>;
    "expected_revision"?: number;
    "root"?: string;
  };
  strategy: {
    "rationale"?: string;
    "basis_refs"?: Array<string>;
    "expected_revision"?: number;
    "event_id"?: string;
    "root"?: string;
    "strategy_operation": "plan" | "review";
    "plan"?: {
      "id": string;
      "claim_id"?: string;
      "node_id"?: string;
      "objective": string;
      "rationale": string;
      "steps"?: Array<Record<string, unknown>>;
      "alternatives"?: Array<Record<string, unknown>>;
      "stop_conditions"?: Array<string>;
      "switch_conditions"?: Array<string>;
      "status"?: "proposed" | "active" | "superseded" | "completed" | "blocked";
      "supersedes_id"?: string;
    };
    "review"?: {
      "id": string;
      "claim_id"?: string;
      "decision": "continue" | "switch" | "stop" | "blocked";
      "rationale": string;
      "selected_strategy_id"?: string;
      "trigger_refs"?: Array<string>;
      "attempt_refs"?: Array<string>;
      "previous_strategy_id"?: string;
      "alternatives_considered"?: Array<Record<string, unknown>>;
      "node_id"?: string;
    };
  };
  interpretation: {
    "rationale"?: string;
    "basis_refs"?: Array<string>;
    "expected_revision"?: number;
    "event_id"?: string;
    "root"?: string;
    "interpretation": {
      "id": string;
      "claim_id"?: string;
      "node_id"?: string;
      "attempt_ref": string;
      "summary": string;
      "outcome": "supports" | "contradicts" | "inconclusive" | "invalid";
      "kind": "result" | "observation" | "execution_issue";
      "direct_evidence_refs"?: Array<string>;
      "comparison_evidence_refs"?: Array<string>;
      "background_evidence_refs"?: Array<string>;
      "result_receipt_ref"?: string;
      "execution_observation_ref"?: string;
      "supersedes_id"?: string;
      "finding_ids"?: Array<string>;
      "gate_ids"?: Array<string>;
    };
  };
  checkpoint: {
    "rationale"?: string;
    "basis_refs"?: Array<string>;
    "expected_revision"?: number;
    "event_id"?: string;
    "root"?: string;
    "checkpoint": {
      "id"?: string;
      "turn_id"?: string;
      "disposition": "continue_required" | "waiting_external" | "deferred" | "blocked" | "terminal" | "user_input_required";
      "reason": string;
      "claim_ids"?: Array<string>;
      "node_ids"?: Array<string>;
      "unresolved_refs"?: Array<string>;
      "map_revision"?: number;
    };
  };
  jobStart: {
    "node_id"?: string;
    "attempt_id"?: string;
    "request_id"?: string;
    "validator_id"?: string;
    "validator_version"?: string;
    "input_artifact_ids"?: Array<string>;
    "work_id"?: string;
    "repeat"?: {
      "predecessor_job_id": string;
      "reason": string;
      "budget": string;
    };
    "request_file"?: string;
    "prepared_ref"?: string;
    "request_sha256"?: string;
    "metadata"?: Record<string, unknown>;
    "command"?: Array<string>;
    "cwd"?: string;
    "environment"?: Record<string, unknown>;
    "inputs"?: Array<string | {
      "source": string;
      "sha256"?: string;
      "destination": string;
    }>;
    "outputs"?: Array<{
      "path": string;
      "required"?: boolean;
      "min_bytes"?: number;
      "recursive"?: boolean;
      "media_type"?: string;
    }>;
    "timeout_seconds"?: number;
    "platform"?: string;
    "root"?: string;
  };
  jobStatus: {
    "job_id"?: string;
    "attempt_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  jobCollect: {
    "job_id"?: string;
    "attempt_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  jobCancel: {
    "job_id"?: string;
    "attempt_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  jobProbe: {
    "platform"?: string;
    "root"?: string;
  };
  jobReconcile: {
    "job_id"?: string;
    "attempt_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  artifactRegister: {
    "path": string;
    "node_id"?: string;
    "job_id"?: string;
    "media_type"?: string;
    "root"?: string;
  };
  artifactCreate: {
    "content": string;
    "name": string;
    "node_id"?: string;
    "media_type"?: string;
    "root"?: string;
  };
  artifactRead: {
    "artifact_id"?: string;
    "artifact_ref"?: string;
    "offset"?: number;
    "limit"?: number;
    "root"?: string;
  };
  artifactDerive: {
    "input_artifact_ids": Array<string>;
    "operation": string;
    "parameters"?: Record<string, unknown>;
    "root"?: string;
  };
  artifactLink: {
    "artifact_id"?: string;
    "artifact_ref"?: string;
    "subject_id": string;
    "relation"?: "supports" | "contradicts" | "qualifies" | "derived_from" | "documents";
    "root"?: string;
  };
}
