// Generate structural TypeScript declarations from the actual model tool schemas.
// Value bounds and conditional constraints remain enforced by JSON Schema.
import { readFile, writeFile } from "node:fs/promises";
import Type from "../apps/app-server/pi-runtime-deps.mjs";
import { createPublicToolContracts } from "../packages/agent-runtime/host-api/tools.mjs";

function typeFor(schema, depth = 0) {
  if (schema === true) return "unknown";
  if (schema === false) return "never";
  if (schema.$ref) throw new Error(`Unresolved tool schema reference: ${schema.$ref}`);
  if ("const" in schema) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map(value => JSON.stringify(value)).join(" | ");
  const branches = schema.anyOf || schema.oneOf;
  if (branches && !schema.properties) return branches.map(value => typeFor(value, depth)).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map(type => typeFor({ ...schema, type }, depth)).join(" | ");
  if (schema.type === "array") return `Array<${typeFor(schema.items || {}, depth)}>`;
  if (schema.type === "object" || schema.properties) {
    const required = new Set(schema.required || []);
    const fields = Object.entries(schema.properties || {}).map(([key, value]) =>
      `${"  ".repeat(depth + 1)}${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${typeFor(value, depth + 1)};`);
    if (schema.additionalProperties !== false && !fields.length) {
      return `Record<string, ${typeFor(schema.additionalProperties || {}, depth)}>`;
    }
    if (schema.additionalProperties && fields.length) fields.push(`${"  ".repeat(depth + 1)}[key: string]: unknown;`);
    return fields.length ? `{\n${fields.join("\n")}\n${"  ".repeat(depth)}}` : "Record<string, never>";
  }
  return { integer: "number", number: "number", boolean: "boolean", null: "null", string: "string" }[schema.type] || "unknown";
}

const schemas = createPublicToolContracts(Type);
const output = ["// Generated by scripts/update_tool_types.mjs. Do not edit independently.",
  "export interface ToolParameters {", ...Object.entries(schemas).map(([key, tool]) =>
    `  ${key}: ${typeFor(tool.parameters, 1)};`), "}", ""].join("\n");
const path = new URL("../packages/agent-runtime/host-api/tool-parameters.d.mts", import.meta.url);
if (process.argv.includes("--check")) {
  if (await readFile(path, "utf8") !== output) throw new Error("Tool types are stale; run scripts/update_tool_types.mjs");
} else await writeFile(path, output);
