import { readFile, writeFile } from "node:fs/promises";
import { PUBLIC_TOOL_NAMES } from "../apps/agent/tools/contracts.mjs";
for (const suffix of [".md", ".zh-CN.md"]) {
  const text = [suffix.includes("zh") ? "# 公开工具契约" : "# Public tool contract", "",
    "Generated by scripts/update_public_contract.mjs. Tool parameters are defined by the runtime schemas; use returned references.", "",
    "```text", ...new Set(Object.values(PUBLIC_TOOL_NAMES)), "```", "",
    "Research Memory retains original requirements, problem Nodes, immutable Results and explicit relations. Job Runtime owns execution; Artifact Store owns payloads and provenance. Research updates do not gate tools or trigger next_run.", ""].join("\n");
  const path = new URL(`../skills/research-workflow/references/public_contract${suffix}`, import.meta.url);
  if (process.argv.includes("--check")) {
    if (await readFile(path,"utf8") !== text) throw Error("public Skill contract is stale");
  } else await writeFile(path,text);
}
