import { readFile, writeFile } from "node:fs/promises";
import { PUBLIC_TOOL_NAMES } from "../packages/agent-runtime/host-api/tools.mjs";
import { RESEARCH_DISPOSITIONS } from "../packages/research-state-bridge/ports.mjs";

const target = new URL("../extensions/core/skills/orchestration/references/public_contract.md", import.meta.url);
const text = ["# Public tool and checkpoint contract", "",
  "Generated by scripts/update_public_contract.mjs from the public tool registry and Research State contract. Do not edit independently.", "",
  "Tool parameters come from the registered runtime schema; tool results carry actual IDs.", "",
  "```text", ...new Set(Object.values(PUBLIC_TOOL_NAMES)), "```", "",
  "Checkpoint dispositions:", "", "```text", ...RESEARCH_DISPOSITIONS, "```", "",
  "Research State computes eligible_node_ids, ready_node_ids, blocked_node_ids, running_attempt_ids, needs_checkpoint and durable continuation admission. Host consumes State tool_admission; Monitor consumes State wake admission. Skills do not maintain copies of those rules.", "",
].join("\n");
const translations = [
  [target, text],
  [new URL("../extensions/core/skills/orchestration/references/public_contract.zh-CN.md", import.meta.url),
   text.replace("# Public tool and checkpoint contract", "# 公开工具与 checkpoint 契约").replace("Generated by scripts/update_public_contract.mjs from the public tool registry and Research State contract. Do not edit independently.", "由 scripts/update_public_contract.mjs 从公开工具注册表与 Research State 契约生成，不单独编辑。").replace("Tool parameters come from the registered runtime schema; tool results carry actual IDs.", "工具参数以运行时注册的 schema 为准，引用使用工具返回的真实 ID。").replace("Checkpoint dispositions:", "Checkpoint disposition：").replace("Research State computes eligible_node_ids, ready_node_ids, blocked_node_ids, running_attempt_ids, needs_checkpoint and durable continuation admission. Host consumes State tool_admission; Monitor consumes State wake admission. Skills do not maintain copies of those rules.", "Research State 计算 eligible_node_ids、ready_node_ids、blocked_node_ids、running_attempt_ids、needs_checkpoint 与持久接续准入。Host 使用 State 的 tool_admission，Monitor 使用 State 的 wake 准入；Skill 不另行维护这些规则。")],
];
for (const [path, content] of translations) {
  if (process.argv.includes("--check")) {
    if (await readFile(path, "utf8") !== content) throw new Error("public Skill contract is stale; run scripts/update_public_contract.mjs");
  } else await writeFile(path, content);
}
