// Generated by tools/contracts/sync_ts_phone.py from contracts/ts-phone.
// Canonical field constraints belong to ts-phone; command field selection belongs to TSPi.

export const BRIDGE_PROTOCOL_VERSION = "ts-phone-bridge/3" as const;

export interface BridgeRegisteredRecord {
  protocolVersion: typeof BRIDGE_PROTOCOL_VERSION;
  type: "bridge.registered";
  workspaceId: string;
  sessionId: string;
  instanceEpoch: string;
}

export interface BridgePromptCommand {
  protocolVersion: typeof BRIDGE_PROTOCOL_VERSION;
  type: "command.prompt";
  workspaceId: string;
  sessionId: string;
  instanceEpoch: string;
  sessionGeneration: number;
  requestId: string;
  clientMessageId: string;
  message: string;
  clientKind?: "phone" | "terminal";
}

export interface BridgeAbortCommand {
  protocolVersion: typeof BRIDGE_PROTOCOL_VERSION;
  type: "command.abort";
  workspaceId: string;
  sessionId: string;
  instanceEpoch: string;
  sessionGeneration: number;
  requestId: string;
  agentRunId: string;
}

export interface BridgeApprovalResponse {
  protocolVersion: typeof BRIDGE_PROTOCOL_VERSION;
  type: "approval.respond";
  workspaceId: string;
  sessionId: string;
  instanceEpoch: string;
  sessionGeneration: number;
  requestId: string;
  approvalId: string;
  approved: boolean;
}

export type BridgeServerRecord = BridgeRegisteredRecord | BridgePromptCommand | BridgeAbortCommand | BridgeApprovalResponse;

const RECORDS: Record<string, { required: string[]; optional: string[] }> = {
  "bridge.registered": {
    "required": [
      "workspaceId",
      "sessionId",
      "instanceEpoch"
    ],
    "optional": []
  },
  "command.prompt": {
    "required": [
      "workspaceId",
      "sessionId",
      "instanceEpoch",
      "sessionGeneration",
      "requestId",
      "clientMessageId",
      "message"
    ],
    "optional": [
      "clientKind"
    ]
  },
  "command.abort": {
    "required": [
      "workspaceId",
      "sessionId",
      "instanceEpoch",
      "sessionGeneration",
      "requestId",
      "agentRunId"
    ],
    "optional": []
  },
  "approval.respond": {
    "required": [
      "workspaceId",
      "sessionId",
      "instanceEpoch",
      "sessionGeneration",
      "requestId",
      "approvalId",
      "approved"
    ],
    "optional": []
  }
};
const FIELDS: Record<string, Field> = {
  "agentRunId": {
    "type": "string",
    "pattern": "^[A-Za-z0-9._:-]{1,160}$"
  },
  "approvalId": {
    "type": "string",
    "pattern": "^[A-Za-z0-9._:-]{1,160}$"
  },
  "approved": {
    "type": "boolean"
  },
  "clientKind": {
    "enum": [
      "phone",
      "terminal"
    ]
  },
  "clientMessageId": {
    "type": "string",
    "pattern": "^[A-Za-z0-9._:-]{1,160}$"
  },
  "instanceEpoch": {
    "type": "string",
    "pattern": "^[A-Za-z0-9._:-]{1,160}$"
  },
  "message": {
    "type": "string",
    "minLength": 1,
    "maxLength": 65536
  },
  "requestId": {
    "type": "string",
    "pattern": "^[A-Za-z0-9._:-]{1,160}$"
  },
  "sessionGeneration": {
    "type": "integer",
    "minimum": 1
  },
  "sessionId": {
    "type": "string",
    "pattern": "^[A-Za-z0-9._:-]{1,160}$"
  },
  "workspaceId": {
    "type": "string",
    "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$"
  }
};

interface Field {
  type?: string;
  enum?: unknown[];
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
}

export function parseBridgeServerRecord(value: unknown): BridgeServerRecord {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Bridge record must be an object");
  const record = value as Record<string, unknown>;
  if (record.protocolVersion !== BRIDGE_PROTOCOL_VERSION) throw new Error("Unsupported TS Phone bridge protocol");
  const type = record.type;
  if (typeof type !== "string" || !Object.hasOwn(RECORDS, type)) {
    throw new Error("Unsupported TS Phone bridge record: " + String(type));
  }
  const policy = RECORDS[type];
  const parsed: Record<string, unknown> = { protocolVersion: BRIDGE_PROTOCOL_VERSION, type };
  for (const name of [...policy.required, ...policy.optional]) {
    if (record[name] === undefined && policy.optional.includes(name)) continue;
    validateField(record[name], name, FIELDS[name]);
    parsed[name] = record[name];
  }
  // Missing clientKind and explicit phone have identical adapter semantics.
  if (type === "command.prompt" && parsed.clientKind === "phone") delete parsed.clientKind;
  return parsed as unknown as BridgeServerRecord;
}

function validateField(value: unknown, name: string, field: Field): void {
  if (field.enum && !field.enum.includes(value)) throw new Error(name + " is invalid");
  if (field.type === "string") {
    if (typeof value !== "string"
      || (field.minLength !== undefined && [...value].length < field.minLength)
      || (field.maxLength !== undefined && [...value].length > field.maxLength)
      || (field.pattern !== undefined && !new RegExp(field.pattern).test(value))) {
      throw new Error(name + " is invalid");
    }
  } else if (field.type === "integer") {
    if (!Number.isSafeInteger(value) || (field.minimum !== undefined && (value as number) < field.minimum)) {
      throw new Error(name + " is invalid");
    }
  } else if (field.type === "boolean" && typeof value !== "boolean") {
    throw new Error(name + " must be boolean");
  }
}
