"""Path-restricted calculation preparation and result collection.

This module owns operational artifacts only. It never mutates canonical TS
research state or turns program output into a workspace claim verdict.
"""

from __future__ import annotations

import hashlib
import json
import os
import posixpath
import tempfile
from dataclasses import asdict, replace
from pathlib import Path, PurePosixPath
from typing import Any, Callable

from ts_backends.ase_neb import prepare_ase_neb
from ts_backends.base import BackendTask, PreparedTask
from ts_backends.crest import (
    CREST_REQUIRED_ARTIFACTS,
    parse_crest_artifacts,
    prepare_crest,
    write_crest_parse_artifacts,
)
from ts_backends.gaussian import (
    parse_irc_log,
    parse_log,
    prepare_gaussian,
    read_gjf_route,
    route_settings,
    write_irc_parse_artifacts,
    write_parse_artifacts,
)
from ts_backends.qbics_dmecp import prepare_qbics_dmecp
from ts_backends.xtb import (
    XTB_REQUIRED_ARTIFACTS,
    parse_xtb_artifacts,
    prepare_xtb,
    write_xtb_parse_artifacts,
)
from ts_backends.xtb_scan import parse_xtb_scan_control
from ts_backends.xyz import xyz_frame_metadata
from ts_remote import lifecycle as remote_lifecycle
from ts_remote.config import load_config as load_remote_config
from ts_remote.errors import (
    RemoteCancellationAmbiguous,
    RemoteConfigurationError,
    RemotePreSubmitError,
    RemoteSubmissionAmbiguous,
    RemoteSubmissionRejected,
)
from ts_remote.models import RemoteJobConfig, RemoteResources
from ts_workspace.io import now_iso, read_json, sha256_json, write_json
from ts_workspace.identity import WorkspaceIdentityError, workspace_id

from .artifacts import resolve_input_artifacts, verify_input_bindings
from .capabilities import BACKEND_TASK_INPUT_ROLES
from .contracts import ComputeContractError, validate_compute_contract


INTENT_SCHEMA = "calculation_intent.schema.json"
REQUEST_SCHEMA = "calculation_request.schema.json"
RESULT_SCHEMA = "calculation_result.schema.json"
MAX_TAIL_BYTES = 32 * 1024
BACKEND_PREPARERS: dict[str, Callable[[BackendTask], PreparedTask]] = {
    "gaussian": prepare_gaussian,
    "xtb": prepare_xtb,
    "crest": prepare_crest,
    "ase_neb": prepare_ase_neb,
    "qbics_dmecp": prepare_qbics_dmecp,
}
BACKENDS: dict[str, dict[str, tuple[set[str], Callable[[BackendTask], PreparedTask]]]] = {
    backend: {
        task_type: (set(input_roles), BACKEND_PREPARERS[backend])
        for task_type, input_roles in tasks.items()
    }
    for backend, tasks in BACKEND_TASK_INPUT_ROLES.items()
}
OPERATIONS = {"prepare", "submit", "inspect", "collect", "cancel", "parse"}


def create_calculation_intent(root: str | Path, request: dict[str, Any]) -> dict[str, Any]:
    """Materialize one semantic request as an immutable attempt intent."""

    workspace = _workspace_root(root)
    validate_compute_contract(REQUEST_SCHEMA, request)
    act_id = str(request["act_id"])
    backend = str(request["backend"])
    task_type = str(request["task_type"])
    if backend not in BACKENDS or task_type not in BACKENDS[backend]:
        raise ComputeContractError(f"unsupported {backend} task_type: {task_type}")
    act = _load_act(workspace, act_id)
    if act.get("status") != "open":
        raise ComputeContractError(f"calculation intent creation requires an open ResearchAct: {act_id}")
    if "output" in request["settings"]:
        raise ComputeContractError("calculation request settings.output is generated by the compute kernel")

    required_inputs, _ = BACKENDS[backend][task_type]
    input_refs, input_bindings = resolve_input_artifacts(
        workspace,
        request["input_artifacts"],
        required_inputs,
    )
    attempts_dir = workspace / "acts" / act_id / "attempts"
    prefix = _intent_id_prefix(act_id, backend, task_type)
    sequence = _next_intent_sequence(attempts_dir, prefix)

    while sequence <= 9999:
        intent_id = f"{prefix}_{sequence:04d}"
        intent = {
            "schema_version": "ts-calculation-intent/4",
            "intent_id": intent_id,
            "act_id": act_id,
            "purpose": request["purpose"],
            "attempt_kind": request["attempt_kind"],
            "recalculation_ref": request["recalculation_ref"],
            "backend": backend,
            "task_type": task_type,
            "input_refs": input_refs,
            "input_bindings": input_bindings,
            "settings": request["settings"],
            "expected_artifacts": [],
            "execution_target": _materialize_execution_target(
                workspace,
                request["execution_target"],
                act_id,
                intent_id,
            ),
            "dry_run": request["dry_run"],
        }
        intent["expected_artifacts"] = _default_expected_artifact_refs(workspace, intent)
        _validate_intent(intent)
        _validate_intent_act_scope(workspace, intent, act)
        prepared = _prepared_task_for_intent(workspace, intent)
        execution_policy = _execution_policy_for_prepare(workspace, intent)
        if execution_policy["kind"] == "remote":
            _require_unique_remote_basenames(prepared.expected_artifacts)
            _remote_stdout_name(asdict(prepared))

        intent_ref, _ = _record_refs(act_id, intent_id)
        attempt_dir = workspace / "acts" / act_id / "attempts" / intent_id
        try:
            attempt_dir.mkdir(parents=True)
        except FileExistsError:
            sequence += 1
            continue
        intent_path = workspace / intent_ref
        try:
            write_json(intent_path, intent)
        except Exception:
            intent_path.with_name(f"{intent_path.name}.tmp").unlink(missing_ok=True)
            try:
                attempt_dir.rmdir()
            except OSError:
                pass
            try:
                attempts_dir.rmdir()
            except OSError:
                pass
            raise
        return {
            "schema_version": "ts-calculation-intent-created/2",
            "intent_id": intent_id,
            "intent_ref": intent_ref,
            "intent_digest": sha256_json(intent),
            "act_id": act_id,
            "backend": backend,
            "task_type": task_type,
            "input_refs": input_refs,
            "input_bindings": input_bindings,
            "expected_artifacts": intent["expected_artifacts"],
            "execution_target": intent["execution_target"],
            "intent": intent,
        }
    raise ComputeContractError(f"calculation intent sequence exhausted for {prefix}")


def preflight_calculation(
    root: str | Path,
    operation: str,
    act_id: str,
    backend: str,
    *,
    intent_file: str | Path | None = None,
    intent_id: str | None = None,
    artifact_ref: str | None = None,
) -> dict[str, Any]:
    workspace = _workspace_root(root)
    if operation not in OPERATIONS:
        raise ComputeContractError(f"unsupported compute operation: {operation}")
    if backend not in BACKENDS:
        raise ComputeContractError(f"unsupported compute backend: {backend}")
    if operation == "prepare":
        if intent_file is None or intent_id is not None:
            raise ComputeContractError("prepare preflight requires intent_file and forbids intent_id")
        intent_path, intent_ref = _intent_source(workspace, intent_file)
        intent = _read_object(intent_path, "calculation intent")
        _validate_intent(intent)
        _require_request_scope(intent, act_id, backend)
        act = _load_act(workspace, act_id)
        if act.get("status") != "open":
            raise ComputeContractError(f"calculation preparation requires an open ResearchAct: {act_id}")
        _validate_intent_act_scope(workspace, intent, act)
        prepared = _prepared_task_for_intent(workspace, intent)
        execution_policy = _execution_policy_for_prepare(workspace, intent)
        if execution_policy["kind"] == "remote":
            _require_unique_remote_basenames(prepared.expected_artifacts)
            _remote_stdout_name(asdict(prepared))
    else:
        if intent_id is None or intent_file is not None:
            raise ComputeContractError(f"{operation} preflight requires intent_id and forbids intent_file")
        workspace, intent, prepared_record = _load_prepared(workspace, intent_id)
        _require_request_scope(intent, act_id, backend)
        intent_ref = str(prepared_record["intent_ref"])
        execution_policy = _prepared_execution_policy(prepared_record)
        if operation in {"submit", "inspect", "collect", "cancel"}:
            _require_remote_execution(execution_policy, operation)
        if operation in {"submit", "cancel"} and intent.get("dry_run") is not False:
            raise ComputeContractError(f"{operation} requires an intent with dry_run=false")
        if operation == "parse":
            if artifact_ref is None:
                raise ComputeContractError("parse preflight requires artifact_ref")
            normalized_artifact = _workspace_ref(workspace, artifact_ref, read=True)
            _require_calculation_output_ref(intent, normalized_artifact)
            artifact_ref = normalized_artifact
    status = _read_local_status(workspace, intent)
    if operation == "collect":
        _collection_program_status(workspace, intent, prepared_record, execution_policy)
    if operation in {"submit", "cancel"}:
        control = _read_control_result(workspace, intent, operation)
        if control is not None and control.get("state") == "unknown":
            raise ComputeContractError(
                f"{operation} refuses automatic replay from durable state unknown"
            )
        if operation == "submit" and control is not None and control.get("state") != "submitted":
            if not _control_allows_same_submission_retry(control):
                raise ComputeContractError(
                    f"submit refuses automatic replay from durable state {control.get('state', 'unknown')}"
                )
        if control is None and _read_control_guard(workspace, intent, operation) is not None:
            raise ComputeContractError(
                f"{operation} has a durable in-progress guard without a final result; manual reconciliation is required"
            )
        if operation == "submit" and (control is None or control.get("state") != "submitted"):
            verify_input_bindings(workspace, intent)
    if operation == "cancel" and status is None:
        raise ComputeContractError("cancel requires a prior local submission status")
    if operation == "cancel" and status is not None:
        _require_cancellable_status(status)
        if not isinstance(status.get("job_id"), str) or not status.get("job_id"):
            raise ComputeContractError("cancel requires a prior inspect with a bound remote job_id")
    return {
        "schema_version": "ts-compute-binding/1",
        "operation": operation,
        "act_id": str(intent["act_id"]),
        "backend": str(intent["backend"]),
        "intent_id": str(intent["intent_id"]),
        "intent_ref": intent_ref,
        "intent_digest": sha256_json(intent),
        "artifact_ref": artifact_ref,
        "execution_kind": execution_policy["kind"],
        "profile": execution_policy.get("profile"),
        "remote_dir": execution_policy.get("remote_dir"),
        "job_id": status.get("job_id") if status else None,
        "state": status.get("state") if status else None,
        "execution_summary": _execution_summary(execution_policy),
    }


def prepare_calculation(
    root: str | Path,
    intent_file: str | Path,
    expected_intent_digest: str | None = None,
) -> dict[str, Any]:
    workspace = _workspace_root(root)
    intent_path, _ = _intent_source(workspace, intent_file)
    intent = _read_object(intent_path, "calculation intent")
    _validate_intent(intent)
    _require_expected_intent_digest(intent, expected_intent_digest)
    act_id = str(intent["act_id"])
    act = _load_act(workspace, act_id)
    if act.get("status") != "open":
        raise ComputeContractError(f"calculation preparation requires an open ResearchAct: {act_id}")
    _validate_intent_act_scope(workspace, intent, act)

    prepared = _prepared_task_for_intent(workspace, intent)
    execution_policy = _execution_policy_for_prepare(workspace, intent)
    if execution_policy["kind"] == "remote":
        _require_unique_remote_basenames(prepared.expected_artifacts)
        _remote_stdout_name(asdict(prepared))

    intent_ref, prepared_ref = _record_refs(act_id, str(intent["intent_id"]))
    intent_path = workspace / intent_ref
    prepared_path = workspace / prepared_ref
    _write_once(intent_path, intent, "intent_id")
    prepared_record = {
        "schema_version": "ts-compute-prepared/1",
        "intent_id": intent["intent_id"],
        "act_id": act_id,
        "intent_ref": intent_ref,
        "intent_digest": sha256_json(intent),
        "attempt_kind": intent["attempt_kind"],
        "prepared_at": now_iso(),
        "prepared_task": asdict(prepared),
        "execution_policy": execution_policy,
    }
    if prepared_path.exists():
        existing = _read_object(prepared_path, "prepared calculation")
        comparable = {key: value for key, value in existing.items() if key != "prepared_at"}
        current = {key: value for key, value in prepared_record.items() if key != "prepared_at"}
        if comparable != current:
            raise ComputeContractError(f"intent_id already has different prepared metadata: {intent['intent_id']}")
        prepared_record = existing
    else:
        write_json(prepared_path, prepared_record)

    result = _result(
        intent,
        state="prepared",
        program_status="not_run",
        artifact_refs=[intent_ref, prepared_ref, *prepared.input_paths],
        provenance={
            "prepared_at": prepared_record["prepared_at"],
            "intent_digest": prepared_record["intent_digest"],
            "backend": prepared.backend,
            "task_type": intent["task_type"],
            "command": prepared.command,
            "expected_artifacts": prepared.expected_artifacts,
            "execution_target": execution_policy,
        },
    )
    return {"intent": intent, "prepared": prepared_record, "result": result}


def submit_calculation(
    root: str | Path,
    intent_id: str,
    expected_intent_digest: str | None = None,
) -> dict[str, Any]:
    workspace, intent, prepared = _load_prepared(root, intent_id, expected_intent_digest)
    policy = _prepared_execution_policy(prepared)
    _require_remote_execution(policy, "submit")
    if intent.get("dry_run") is not False:
        raise ComputeContractError("submit requires an intent with dry_run=false")
    existing = _read_control_result(workspace, intent, "submit")
    if existing is not None:
        if existing.get("state") == "submitted":
            return existing
        if not _control_allows_same_submission_retry(existing):
            raise ComputeContractError(
                f"submit refuses automatic replay from durable state {existing.get('state', 'unknown')}"
            )
    verify_input_bindings(workspace, intent)

    remote_config = _remote_job_config(workspace, intent, prepared, require_inputs=True)
    control_attempt = _claim_control(workspace, intent, "submit")
    try:
        receipt = remote_lifecycle.submit(remote_config)
    except Exception as exc:
        staging_failure = isinstance(exc, RemotePreSubmitError)
        rejected_failure = isinstance(exc, RemoteSubmissionRejected)
        known_failure = staging_failure or rejected_failure
        effect_attempted = not staging_failure
        ambiguous_result = exc.record if isinstance(exc, RemoteSubmissionAmbiguous) else {}
        rejected_result = exc.record if isinstance(exc, RemoteSubmissionRejected) else {}
        if staging_failure:
            failure_phase = exc.phase
            failure_type = type(exc.cause).__name__
            failure_message = str(exc.cause)[:2000]
            error_class = "remote_staging_failed"
        elif rejected_failure:
            failure_phase = "scheduler_accept"
            failure_type = type(exc).__name__
            failure_message = str(rejected_result.get("error", exc))[:2000]
            error_class = "scheduler_submission_rejected"
        else:
            failure_phase = str(ambiguous_result.get("phase") or "submit_request")
            failure_type = type(exc).__name__
            failure_message = str(exc)[:2000]
            error_class = "submission_ambiguous"
        ambiguous_job_id = (
            str(ambiguous_result.get("job_id"))
            if isinstance(ambiguous_result.get("job_id"), str)
            else None
        )
        result = _result(
            intent,
            job_id=ambiguous_job_id,
            state="failed" if known_failure else "unknown",
            program_status="not_run",
            error_class=error_class,
            control=_control_outcome(
                operation="submit",
                phase=failure_phase,
                effect_outcome="failed" if known_failure else "unknown",
                effect_attempted=effect_attempted,
                retry_disposition=(
                    "retry_same_submission"
                    if staging_failure
                    else "new_intent"
                    if rejected_failure
                    else "reconcile_only"
                ),
                reconciliation_required=not known_failure,
                submission_id=(
                    remote_config.submission_id
                ),
                job_id=ambiguous_job_id,
            ),
            provenance={
                "profile": policy["profile"],
                "scheduler": "torque",
                "remote_dir": policy["remote_dir"],
                "observed_at": now_iso(),
                "failure_type": failure_type,
                "failure_message": failure_message,
                "server_submission_state": (
                    rejected_result.get("state")
                    if rejected_failure
                    else ambiguous_result.get("state")
                ),
                "submission_phase": failure_phase,
                "submission_attempted": effect_attempted,
                "retry_safe": staging_failure,
            },
        )
        _write_control_result(workspace, intent, "submit", result, control_attempt)
        _write_status(workspace, intent, result)
        return result

    receipt_ref = _receipt_ref(intent)
    _write_bound_record(
        workspace / receipt_ref,
        remote_lifecycle.receipt_dict(receipt),
        "remote receipt",
    )
    result = _result(
        intent,
        job_id=receipt.scheduler_id,
        state="submitted",
        program_status="not_run",
        artifact_refs=[receipt_ref],
        control=_control_outcome(
            operation="submit",
            phase="receipt_persist",
            effect_outcome="succeeded",
            effect_attempted=True,
            retry_disposition="none",
            reconciliation_required=False,
            submission_id=receipt.submission_id,
            job_id=receipt.scheduler_id,
        ),
        provenance={
            "profile": policy["profile"],
            "scheduler": receipt.scheduler,
            "remote_dir": policy["remote_dir"],
            "submitted_at": receipt.submitted_at,
            "receipt_ref": receipt_ref,
            "submission_id": receipt.submission_id,
        },
    )
    _write_control_result(workspace, intent, "submit", result, control_attempt)
    _write_status(workspace, intent, result)
    return result


def calculation_status(
    root: str | Path,
    intent_id: str,
    expected_intent_digest: str | None = None,
) -> dict[str, Any]:
    workspace, intent, prepared = _load_prepared(root, intent_id, expected_intent_digest)
    policy = _prepared_execution_policy(prepared)
    _require_remote_execution(policy, "inspect")
    config = _remote_job_config(workspace, intent, prepared)
    submitted = _read_control_result(workspace, intent, "submit")
    if submitted is None or submitted.get("state") != "submitted":
        try:
            record = remote_lifecycle.read_submission_record(config)
        except Exception:
            record = None
        if isinstance(record, dict) and record.get("state") == "accepted":
            _reconcile_remote_submit(workspace, intent, config, record)
            submitted = _read_control_result(workspace, intent, "submit")
    if submitted is None or submitted.get("state") != "submitted":
        raise ComputeContractError("inspect requires a durable or reconciled scheduler submission")
    job_id = submitted.get("job_id")
    if not isinstance(job_id, str) or not job_id:
        raise ComputeContractError("inspect requires a bound scheduler job_id")
    observed = remote_lifecycle.status(config, job_id)
    _require_matching_job_id(submitted, observed.job_id, "remote status")
    state = observed.state
    program_status = observed.program_status
    error_class = observed.error_class
    exit_status = observed.exit_status
    provenance = {
        "observed_at": now_iso(),
        "profile": policy["profile"],
        "scheduler": "torque",
        "remote_dir": policy["remote_dir"],
        "submission_id": config.submission_id,
        "scheduler_state": observed.scheduler_state,
        "scheduler_query_error": observed.scheduler_query_error,
        "program_record": observed.program_record,
    }
    result = _result(
        intent,
        job_id=job_id,
        state=state,
        program_status=program_status,
        exit_status=exit_status,
        error_class=error_class,
        provenance=provenance,
    )
    _write_status(workspace, intent, result)
    return result


def calculation_tail(
    root: str | Path,
    intent_id: str,
    artifact: str | None = None,
    lines: int = 80,
    expected_intent_digest: str | None = None,
) -> dict[str, Any]:
    workspace, intent, prepared = _load_prepared(root, intent_id, expected_intent_digest)
    if not 1 <= int(lines) <= 500:
        raise ComputeContractError("tail lines must be between 1 and 500")
    policy = _prepared_execution_policy(prepared)
    _require_remote_execution(policy, "inspect")
    config = _remote_job_config(workspace, intent, prepared)
    target = artifact or config.stdout_name
    allowed = {
        *config.expected_artifacts,
        config.stdout_name,
        config.stderr_name,
        config.program_status_name,
    }
    if target not in allowed:
        raise ComputeContractError(f"remote artifact is not allowlisted for this intent: {target}")
    text = remote_lifecycle.tail(config, target, int(lines))
    encoded = text.encode("utf-8")
    truncated = len(encoded) > MAX_TAIL_BYTES
    if truncated:
        text = encoded[-MAX_TAIL_BYTES:].decode("utf-8", errors="replace")
    return {
        "schema_version": "ts-calculation-tail/1",
        "intent_id": intent["intent_id"],
        "act_id": intent["act_id"],
        "artifact": target,
        "lines": int(lines),
        "truncated": truncated,
        "text": text,
    }


def collect_calculation(
    root: str | Path,
    intent_id: str,
    artifacts: list[str] | None = None,
    expected_intent_digest: str | None = None,
) -> dict[str, Any]:
    workspace, intent, prepared = _load_prepared(root, intent_id, expected_intent_digest)
    policy = _prepared_execution_policy(prepared)
    _require_remote_execution(policy, "collect")
    expected_names = _expected_remote_names(prepared)
    selected = artifacts or expected_names
    if not selected:
        raise ComputeContractError("calculation intent has no expected artifacts to collect")
    if len(selected) != len(set(selected)) or any(name not in expected_names for name in selected):
        raise ComputeContractError("collect artifacts must be a unique subset of the prepared expected artifacts")
    program_status = _collection_program_status(workspace, intent, prepared, policy)
    output_dir = _remote_output_dir(workspace, intent)
    for path in (output_dir.parent, output_dir):
        if path.is_symlink() or (path.exists() and not path.is_dir()):
            raise ComputeContractError(f"calculation output path is not a physical directory: {path}")
    existing = [name for name in selected if (output_dir / Path(name).name).exists()]
    if existing:
        raise ComputeContractError(f"collect refuses to overwrite existing artifacts: {existing}")
    attempt_dir = output_dir.parent.parent
    with tempfile.TemporaryDirectory(prefix=".collect-", dir=attempt_dir) as temporary:
        staging = Path(temporary)
        config = _remote_job_config(workspace, intent, prepared)
        downloaded, transfer_manifest = remote_lifecycle.collect(config, selected, staging)
        if downloaded != selected:
            raise ComputeContractError("remote collect returned artifacts that differ from the request")
        staged_files = [(name, staging / Path(name).name) for name in downloaded]
        for name, source in staged_files:
            if not source.is_file() or source.is_symlink():
                raise ComputeContractError(f"collected artifact is not a regular file: {name}")
        output_parent_created = not output_dir.parent.exists()
        output_dir_created = not output_dir.exists()
        output_dir.mkdir(parents=True, exist_ok=True)
        moved: list[tuple[Path, Path]] = []
        try:
            for _, source in staged_files:
                destination = output_dir / source.name
                source.replace(destination)
                moved.append((source, destination))
        except Exception:
            for source, destination in reversed(moved):
                if destination.exists() and not source.exists():
                    destination.replace(source)
            if output_dir_created:
                try:
                    output_dir.rmdir()
                except OSError:
                    pass
            if output_parent_created:
                try:
                    output_dir.parent.rmdir()
                except OSError:
                    pass
            raise
    artifact_refs = [
        (output_dir / Path(name).name).resolve().relative_to(workspace).as_posix()
        for name in downloaded
    ]
    result = _result(
        intent,
        state="collected",
        program_status=program_status,
        artifact_refs=artifact_refs,
        provenance={
            "collected_at": now_iso(),
            "profile": policy["profile"],
            "scheduler": "torque",
            "remote_dir": policy["remote_dir"],
            "requested_artifacts": selected,
            "transfer_manifest": transfer_manifest,
        },
    )
    _write_result(workspace, intent, result)
    return result


def cancel_calculation(
    root: str | Path,
    intent_id: str,
    expected_intent_digest: str | None = None,
    expected_job_id: str | None = None,
) -> dict[str, Any]:
    workspace, intent, prepared = _load_prepared(root, intent_id, expected_intent_digest)
    policy = _prepared_execution_policy(prepared)
    _require_remote_execution(policy, "cancel")
    if intent.get("dry_run") is not False:
        raise ComputeContractError("cancel requires an intent with dry_run=false")
    previous = _read_control_result(workspace, intent, "cancel")
    if previous is not None:
        if previous.get("state") == "stopped":
            return previous
        raise ComputeContractError(
            f"cancel refuses automatic replay from durable state {previous.get('state', 'unknown')}"
        )
    current = _read_local_status(workspace, intent)
    if current is None:
        raise ComputeContractError("cancel requires a prior local submission status")
    if current.get("state") == "stopped":
        return current
    _require_cancellable_status(current)

    job_id = current.get("job_id") if isinstance(current.get("job_id"), str) else None
    if job_id is None:
        raise ComputeContractError("cancel requires a prior inspect with a bound remote job_id")
    submitted = _read_control_result(workspace, intent, "submit")
    if submitted is None:
        raise ComputeContractError("remote cancellation requires a durable local submit result")
    _require_matching_job_id(submitted, job_id, "remote cancellation")
    remote_config = _remote_job_config(workspace, intent, prepared)
    if expected_job_id is not None and job_id != expected_job_id:
        raise ComputeContractError("cancel job_id changed after preflight binding")
    control_attempt = _claim_control(workspace, intent, "cancel")
    try:
        cancellation = remote_lifecycle.cancel(remote_config, job_id)
        provenance = {
            "profile": policy["profile"],
            "scheduler": "torque",
            "remote_dir": policy["remote_dir"],
            "cancelled_at": cancellation.get("updated_at", now_iso()),
            "submission_id": remote_config.submission_id,
        }
    except Exception as exc:
        result = _result(
            intent,
            job_id=job_id,
            state="unknown",
            program_status="not_run",
            error_class="cancellation_ambiguous",
            control=_control_outcome(
                operation="cancel",
                phase="cancel_request",
                effect_outcome="unknown",
                effect_attempted=True,
                retry_disposition="reconcile_only",
                reconciliation_required=True,
                submission_id=(
                    remote_config.submission_id
                ),
                job_id=job_id,
            ),
            provenance={
                "profile": policy["profile"],
                "scheduler": "torque",
                "remote_dir": policy["remote_dir"],
                "observed_at": now_iso(),
                "failure_type": type(exc).__name__,
            },
        )
        _write_control_result(workspace, intent, "cancel", result, control_attempt)
        _write_status(workspace, intent, result)
        return result

    result = _result(
        intent,
        job_id=job_id,
        state="stopped",
        program_status="stopped",
        error_class="remote_job_cancelled",
        control=_control_outcome(
            operation="cancel",
            phase="cancel_confirmed",
            effect_outcome="succeeded",
            effect_attempted=True,
            retry_disposition="none",
            reconciliation_required=False,
            submission_id=remote_config.submission_id,
            job_id=job_id,
        ),
        provenance=provenance,
    )
    _write_control_result(workspace, intent, "cancel", result, control_attempt)
    _write_status(workspace, intent, result)
    return result


def parse_calculation(
    root: str | Path,
    intent_id: str,
    artifact_ref: str,
    expected_intent_digest: str | None = None,
) -> dict[str, Any]:
    workspace, intent, prepared = _load_prepared(root, intent_id, expected_intent_digest)
    source_ref = _workspace_ref(workspace, artifact_ref, read=True)
    _require_calculation_output_ref(intent, source_ref)
    prepared_task = prepared["prepared_task"]
    expected = {Path(ref).name for ref in prepared_task["expected_artifacts"]}
    if Path(source_ref).name not in expected:
        raise ComputeContractError("parse artifact basename is outside the prepared expected artifacts")
    source = workspace / source_ref
    backend = str(intent["backend"])
    if backend == "gaussian" and source.suffix.lower() not in {".log", ".out"}:
        raise ComputeContractError("Gaussian parser accepts only .log or .out artifacts")
    if backend == "xtb" and source.name != "xtb.out":
        raise ComputeContractError("xTB parser requires the bound xtb.out artifact")
    if backend == "crest" and source.name != "crest.out":
        raise ComputeContractError("CREST parser requires the bound crest.out artifact")
    if backend not in {"gaussian", "xtb", "crest"}:
        raise ComputeContractError(f"no deterministic parser is exposed for backend: {backend}")

    parse_inputs = _bound_parse_artifacts(workspace, intent, prepared_task, source_ref)
    parser_inputs = [
        {"ref": ref, "sha256": _sha256_file(path)}
        for _, (ref, path) in sorted(parse_inputs.items())
    ]
    xtb_control: Path | None = None
    if backend == "xtb" and intent.get("task_type") == "scan":
        control_ref = _workspace_ref(workspace, str(intent["input_refs"]["control"]), read=True)
        xtb_control = workspace / control_ref
        parser_inputs.append({"ref": control_ref, "sha256": _sha256_file(xtb_control)})

    _, _, output_ref = _runtime_refs(str(intent["act_id"]), str(intent["intent_id"]))
    result_path = workspace / output_ref / "calculation_result.json"
    source_sha256 = _sha256_file(source)
    previous: dict[str, Any] | None = None
    if result_path.is_file():
        previous = _read_object(result_path, "calculation result")
        _validate_bound_result(intent, previous, "calculation result")
        provenance = previous.get("provenance") if isinstance(previous.get("provenance"), dict) else {}
        if previous.get("state") == "parsed":
            same_inputs = provenance.get("parser_inputs") == parser_inputs
            if same_inputs:
                return previous
            raise ComputeContractError(
                "parse refuses to overwrite a result from different source content; use a new intent_id"
            )

    is_irc = backend == "gaussian" and intent.get("task_type") == "irc"
    if backend == "gaussian":
        expected_route = None
        gjf_ref = intent["input_refs"].get("gjf")
        if gjf_ref:
            expected_route = read_gjf_route(workspace / _workspace_ref(workspace, gjf_ref, read=True))
        parsed = parse_irc_log(source) if is_irc else parse_log(source, expected_route=expected_route)
    elif backend == "xtb":
        parsed = parse_xtb_artifacts(
            str(intent["task_type"]),
            {name: path for name, (_, path) in parse_inputs.items()},
            control=xtb_control,
        )
    else:
        parsed = parse_crest_artifacts(
            {name: path for name, (_, path) in parse_inputs.items()}
        )
    summary = parsed.get("summary")
    if not isinstance(summary, dict):
        raise ComputeContractError(f"{backend} parser returned an invalid summary")
    parse_dir = workspace / output_ref / "parsed"
    if parse_dir.exists() and any(parse_dir.iterdir()):
        raise ComputeContractError("parse output directory is non-empty without a matching calculation result")
    if backend == "gaussian" and is_irc:
        write_irc_parse_artifacts(parsed, parse_dir, source.stem, source.name)
    elif backend == "gaussian":
        write_parse_artifacts(parsed, parse_dir, source.stem, source.name)
    elif backend == "xtb":
        write_xtb_parse_artifacts(parsed, parse_dir)
    else:
        write_crest_parse_artifacts(parsed, parse_dir)
    parsed_refs = sorted(path.relative_to(workspace).as_posix() for path in parse_dir.glob("*") if path.is_file())
    raw_refs = sorted(ref for ref, _ in parse_inputs.values())
    program_status, error_class = _parsed_program_outcome(backend, summary)
    result = _result(
        intent,
        job_id=(previous.get("job_id") if previous else None),
        state="parsed",
        program_status=program_status,
        exit_status=(previous.get("exit_status") if previous else None),
        artifact_refs=[*raw_refs, *parsed_refs],
        parser_facts=summary,
        error_class=error_class,
        provenance={
            "parsed_at": now_iso(),
            "source_ref": source_ref,
            "source_sha256": source_sha256,
            "parser_inputs": parser_inputs,
            "parser_name": _parser_name(backend, is_irc),
            "parser_contract": _parser_contract(backend, is_irc),
        },
    )
    _write_result(workspace, intent, result)
    return result


def _bound_parse_artifacts(
    workspace: Path,
    intent: dict[str, Any],
    prepared_task: dict[str, Any],
    source_ref: str,
) -> dict[str, tuple[str, Path]]:
    source = workspace / source_ref
    expected_names = {Path(str(ref)).name for ref in prepared_task["expected_artifacts"]}
    artifacts: dict[str, tuple[str, Path]] = {}
    for name in sorted(expected_names):
        candidate = source.parent / name
        if not candidate.exists():
            continue
        if candidate.is_symlink() or not candidate.is_file():
            raise ComputeContractError(f"parse artifact is not a regular file: {candidate}")
        ref = candidate.resolve().relative_to(workspace).as_posix()
        _require_calculation_output_ref(intent, ref)
        artifacts[name] = (ref, candidate)
    if source.name not in artifacts:
        raise ComputeContractError("parse primary artifact is missing from its bound artifact set")
    return artifacts


def _parsed_program_outcome(backend: str, summary: dict[str, Any]) -> tuple[str, str | None]:
    if backend == "gaussian":
        normal = bool(summary.get("normal_termination"))
        return ("completed", None) if normal else ("failed", "gaussian_error_termination")
    prefix = "xtb" if backend == "xtb" else "crest"
    if not summary.get("execution_completed"):
        return "failed", f"{prefix}_error_termination"
    if not summary.get("artifacts_complete"):
        return "failed", f"{prefix}_artifacts_incomplete"
    if not summary.get("task_completed"):
        return "failed", f"{prefix}_task_incomplete"
    return "completed", None


def _parser_name(backend: str, is_irc: bool) -> str:
    if backend == "gaussian":
        return "ts_backends.gaussian.parse_irc_log" if is_irc else "ts_backends.gaussian.parse_log"
    if backend == "xtb":
        return "ts_backends.xtb.parse_xtb_artifacts"
    return "ts_backends.crest.parse_crest_artifacts"


def _parser_contract(backend: str, is_irc: bool) -> str:
    if backend == "gaussian":
        return "gaussian-irc-parser/1" if is_irc else "gaussian-tsfreq-parser/1"
    return "xtb-task-parser/1" if backend == "xtb" else "crest-conformer-parser/1"


def _validate_backend_request(
    intent: dict[str, Any],
    inputs: dict[str, str],
    workspace: Path,
    *,
    validate_content: bool = True,
) -> None:
    backend = str(intent["backend"])
    task_type = str(intent["task_type"])
    tasks = BACKENDS[backend]
    if task_type not in tasks:
        raise ComputeContractError(f"unsupported {backend} task_type: {task_type}")
    required_inputs, _ = tasks[task_type]
    if set(inputs) != required_inputs:
        missing = sorted(required_inputs - set(inputs))
        unexpected = sorted(set(inputs) - required_inputs)
        raise ComputeContractError(
            f"{backend} input roles must be exactly {sorted(required_inputs)}; "
            f"missing={missing}; unexpected={unexpected}"
        )
    if not validate_content:
        return
    if backend == "xtb" and task_type == "scan":
        try:
            geometry = xyz_frame_metadata(workspace / inputs["xyz"])
            parse_xtb_scan_control(
                workspace / inputs["control"],
                atom_count=int(geometry["atom_count"]),
            )
        except (OSError, UnicodeError, ValueError) as exc:
            raise ComputeContractError(f"invalid xTB scan control input: {exc}") from exc
        return
    if backend != "gaussian":
        return
    gjf = workspace / inputs["gjf"]
    if gjf.suffix.lower() not in {".gjf", ".com"}:
        raise ComputeContractError("Gaussian input must use .gjf or .com")
    flags = route_settings(read_gjf_route(gjf))
    required_flags = {
        "opt": {"has_opt"},
        "freq": {"has_freq"},
        "opt_freq": {"has_opt", "has_freq"},
        "irc": {"has_irc"},
        "sp": set(),
    }[str(intent["task_type"])]
    missing = sorted(flag for flag in required_flags if not flags.get(flag))
    if missing:
        raise ComputeContractError(f"Gaussian route does not match task_type {intent['task_type']}: missing {missing}")


def _intent_id_prefix(act_id: str, backend: str, task_type: str) -> str:
    raw = f"calc_{act_id}_{backend}_{task_type}"
    normalized = "".join(
        char if char.isalnum() or char in "_.-" else "_"
        for char in raw
    )
    return normalized[:123].rstrip("_.-")


def _next_intent_sequence(attempts_dir: Path, prefix: str) -> int:
    sequences = []
    marker = f"{prefix}_"
    if not attempts_dir.is_dir():
        return 1
    for path in attempts_dir.iterdir():
        if not path.is_dir() or not path.name.startswith(marker):
            continue
        suffix = path.name[len(marker):]
        if suffix.isdigit():
            sequences.append(int(suffix))
    return max(sequences, default=0) + 1


def _materialize_execution_target(
    workspace: Path,
    request_target: dict[str, Any],
    act_id: str,
    intent_id: str,
) -> dict[str, Any]:
    if request_target["kind"] == "local":
        return {"kind": "local"}
    try:
        remote_config = load_remote_config()
        profile = remote_config.profile(str(request_target["profile"]))
        resources = RemoteResources.from_mapping(request_target["resources"])
        identity = workspace_id(workspace, create=True)
    except (RemoteConfigurationError, WorkspaceIdentityError) as exc:
        raise ComputeContractError(f"cannot materialize ts_remote target: {exc}") from exc
    _validate_profile_resources(profile, resources)
    remote_dir = str(
        PurePosixPath(profile.remote_root)
        / "workspaces"
        / identity
        / "runs"
        / act_id
        / intent_id
    )
    return {
        "kind": "remote",
        "authority": "execution_mirror",
        "profile": profile.name,
        "workspace_id": identity,
        "remote_dir": remote_dir,
        "resources": asdict(resources),
    }


def _raw_prepared_task(
    workspace: Path,
    intent: dict[str, Any],
    *,
    verify_inputs: bool = True,
) -> PreparedTask:
    if verify_inputs:
        verify_input_bindings(workspace, intent)
    inputs = {}
    for role, ref in intent["input_refs"].items():
        normalized = _workspace_ref(workspace, ref, read=verify_inputs)
        _require_compute_input_ref(normalized)
        inputs[role] = normalized
    _validate_backend_request(
        intent,
        inputs,
        workspace,
        validate_content=verify_inputs,
    )
    backend = str(intent["backend"])
    task_type = str(intent["task_type"])
    _, prepare = BACKENDS[backend][task_type]
    task = BackendTask(
        act_id=str(intent["act_id"]),
        task_type=task_type,
        work_dir=f"acts/{intent['act_id']}",
        inputs=inputs,
        settings={str(key): str(value) for key, value in intent["settings"].items()},
    )
    return prepare(task)


def _default_expected_artifact_refs(workspace: Path, intent: dict[str, Any]) -> list[str]:
    prepared = _raw_prepared_task(workspace, intent)
    names = [Path(ref).name for ref in prepared.expected_artifacts]
    if not names or any(not name or name in {".", ".."} for name in names):
        raise ComputeContractError("backend returned an invalid expected artifact name")
    if len(names) != len(set(names)):
        raise ComputeContractError("backend returned colliding expected artifact names")
    base = f"acts/{intent['act_id']}/attempts/{intent['intent_id']}/outputs"
    return [f"{base}/{name}" for name in names]


def _prepared_task_for_intent(
    workspace: Path,
    intent: dict[str, Any],
    *,
    verify_inputs: bool = True,
) -> PreparedTask:
    prepared = _raw_prepared_task(workspace, intent, verify_inputs=verify_inputs)
    normalized = _normalize_prepared_task(
        workspace,
        str(intent["act_id"]),
        str(intent["intent_id"]),
        prepared,
        intent["expected_artifacts"],
        require_inputs=verify_inputs,
    )
    _validate_required_backend_artifacts(intent, normalized)
    return normalized


def _validate_required_backend_artifacts(intent: dict[str, Any], prepared: PreparedTask) -> None:
    backend = str(intent["backend"])
    task_type = str(intent["task_type"])
    if backend == "xtb":
        required = XTB_REQUIRED_ARTIFACTS[task_type]
    elif backend == "crest":
        required = CREST_REQUIRED_ARTIFACTS
    else:
        return
    names = {Path(ref).name for ref in prepared.expected_artifacts}
    missing = sorted(required - names)
    if missing:
        raise ComputeContractError(
            f"{backend} {task_type} expected_artifacts are missing required files: {missing}"
        )


def _normalize_prepared_task(
    workspace: Path,
    act_id: str,
    intent_id: str,
    prepared: PreparedTask,
    expected_artifacts: list[str],
    *,
    require_inputs: bool = True,
) -> PreparedTask:
    if prepared.act_id != act_id:
        raise ComputeContractError("backend returned a task for a different ResearchAct")
    input_paths = [
        _workspace_ref(workspace, ref, read=require_inputs)
        for ref in prepared.input_paths
    ]
    expected = expected_artifacts or prepared.expected_artifacts
    normalized_expected = []
    for ref in expected:
        normalized = _workspace_ref(workspace, ref, read=False)
        _require_attempt_output_ref(act_id, intent_id, normalized)
        normalized_expected.append(normalized)
    return replace(prepared, input_paths=input_paths, expected_artifacts=normalized_expected)


def _validate_execution_target(target: dict[str, Any]) -> dict[str, Any]:
    if target["kind"] == "local":
        return {"kind": "local"}
    try:
        configured = load_remote_config()
        profile = configured.profile(str(target["profile"]))
        resources = RemoteResources.from_mapping(target["resources"])
    except (KeyError, RemoteConfigurationError) as exc:
        raise ComputeContractError(f"invalid ts_remote target: {exc}") from exc
    _validate_profile_resources(profile, resources)
    return {
        "kind": "remote",
        "authority": "execution_mirror",
        "profile": profile.name,
        "workspace_id": str(target["workspace_id"]),
        "remote_dir": str(target["remote_dir"]),
        "resources": asdict(resources),
    }


def _execution_policy_for_prepare(
    workspace: Path,
    intent: dict[str, Any],
    *,
    create_identity: bool = True,
) -> dict[str, Any]:
    policy = _validate_execution_target(intent["execution_target"])
    if policy["kind"] == "local":
        return policy
    try:
        identity = workspace_id(workspace, create=create_identity)
    except WorkspaceIdentityError as exc:
        raise ComputeContractError(f"cannot bind remote calculation to workspace identity: {exc}") from exc
    configured = load_remote_config()
    profile = configured.profile(str(policy["profile"]))
    expected_dir = str(
        PurePosixPath(profile.remote_root)
        / "workspaces"
        / identity
        / "runs"
        / str(intent["act_id"])
        / str(intent["intent_id"])
    )
    if policy["workspace_id"] != identity or policy["remote_dir"] != expected_dir:
        raise ComputeContractError("remote execution target does not match the workspace-scoped path")
    return policy


def _expected_prepared_execution_policy(
    workspace: Path,
    intent: dict[str, Any],
) -> dict[str, Any]:
    return _execution_policy_for_prepare(workspace, intent, create_identity=False)


def _remote_job_config(
    workspace: Path,
    intent: dict[str, Any],
    prepared: dict[str, Any],
    *,
    require_inputs: bool = False,
) -> RemoteJobConfig:
    target = prepared.get("execution_policy")
    if (
        not isinstance(target, dict)
        or target.get("kind") != "remote"
    ):
        raise ComputeContractError("this operation requires a prepared ts_remote target")
    prepared_task = prepared.get("prepared_task")
    if not isinstance(prepared_task, dict):
        raise ComputeContractError("prepared calculation is missing prepared_task")
    input_paths = tuple(
        workspace / _workspace_ref(workspace, ref, read=require_inputs)
        for ref in prepared_task["input_paths"]
    )
    expected = tuple(Path(ref).name for ref in prepared_task["expected_artifacts"])
    if len(expected) != len(set(expected)):
        raise ComputeContractError("expected remote artifacts have colliding basenames")
    _, _, output_ref = _runtime_refs(str(intent["act_id"]), str(intent["intent_id"]))
    try:
        profile = load_remote_config().profile(str(target["profile"]))
        resources = RemoteResources.from_mapping(target["resources"])
    except RemoteConfigurationError as exc:
        raise ComputeContractError(f"invalid prepared ts_remote target: {exc}") from exc
    _validate_profile_resources(profile, resources)
    command = tuple(_rewritten_remote_command(prepared_task))
    return RemoteJobConfig(
        submission_id=_remote_submission_id(str(target["workspace_id"]), str(intent["intent_id"])),
        intent_id=str(intent["intent_id"]),
        intent_digest=sha256_json(intent),
        act_id=str(intent["act_id"]),
        backend=str(intent["backend"]),
        profile=profile,
        remote_dir=str(target["remote_dir"]),
        resources=resources,
        command=command,
        input_paths=input_paths,
        output_dir=workspace / output_ref / "remote",
        expected_artifacts=expected,
        environment={str(key): str(value) for key, value in prepared_task.get("environment", {}).items()},
        stdout_name=_remote_stdout_name(prepared),
    )


def _prepared_execution_policy(prepared: dict[str, Any]) -> dict[str, Any]:
    policy = prepared.get("execution_policy")
    if not isinstance(policy, dict):
        raise ComputeContractError("prepared calculation has no execution policy")
    return policy


def _require_remote_execution(policy: dict[str, Any], operation: str) -> None:
    if policy.get("kind") != "remote" or not isinstance(policy.get("profile"), str):
        raise ComputeContractError(f"{operation} requires a prepared ts_remote target")


def _execution_summary(
    policy: dict[str, Any],
) -> dict[str, Any]:
    if policy.get("kind") != "remote":
        return {"kind": "local"}
    resources = policy["resources"]
    return {
        "kind": "remote",
        "profile": policy["profile"],
        "scheduler": "torque",
        "workspace_id": policy["workspace_id"],
        "remote_dir": policy["remote_dir"],
        "queue": resources["queue"],
        "nodes": resources["nodes"],
        "ncpus": resources["ncpus"],
        "memory": resources["memory"],
        "walltime": resources["walltime"],
        "ngpus": resources["ngpus"],
    }


def _rewritten_remote_command(prepared_task: dict[str, Any]) -> list[str]:
    command = [str(part) for part in prepared_task["command"]]
    rewrites = {str(ref): Path(str(ref)).name for ref in prepared_task["input_paths"]}
    return [rewrites.get(part, part) for part in command]


def _remote_stdout_name(prepared: dict[str, Any]) -> str:
    prepared_task = prepared.get("prepared_task") if "prepared_task" in prepared else prepared
    if not isinstance(prepared_task, dict):
        raise ComputeContractError("prepared calculation is missing prepared_task")
    backend = prepared_task.get("backend")
    expected = [Path(str(ref)).name for ref in prepared_task.get("expected_artifacts", [])]
    if backend == "gaussian":
        captures = [name for name in expected if Path(name).suffix.lower() in {".log", ".out"}]
        if len(captures) != 1:
            raise ComputeContractError("Gaussian remote execution requires exactly one .log or .out artifact")
        return captures[0]
    if backend == "xtb" and "xtb.out" in expected:
        return "xtb.out"
    return "remote_job.stdout"


def _expected_remote_names(prepared: dict[str, Any]) -> list[str]:
    names = [Path(str(ref)).name for ref in prepared["prepared_task"]["expected_artifacts"]]
    if not names or len(names) != len(set(names)):
        raise ComputeContractError("expected remote artifacts have missing or colliding basenames")
    return names


def _remote_output_dir(workspace: Path, intent: dict[str, Any]) -> Path:
    _, _, output_ref = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    return workspace / output_ref / "remote"


def _remote_submission_id(workspace_identity: str, intent_id: str) -> str:
    bound = f"{workspace_identity}\0{intent_id}"
    digest = hashlib.sha256(bound.encode("utf-8")).hexdigest()[:16]
    return f"tsjob_{workspace_identity}_{intent_id[:60]}_{digest}"


def _receipt_ref(intent: dict[str, Any]) -> str:
    base, _, _ = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    return f"{base}/remote_receipt.json"


def _validate_profile_resources(profile: Any, resources: RemoteResources) -> None:
    if resources.queue not in profile.allowed_queues:
        raise ComputeContractError(
            f"queue {resources.queue!r} is not allowed by ts_remote profile {profile.name}"
        )
    if resources.nodes > profile.max_nodes:
        raise ComputeContractError(
            f"requested nodes={resources.nodes} exceeds profile max_nodes={profile.max_nodes}"
        )


def _reconcile_remote_submit(
    workspace: Path,
    intent: dict[str, Any],
    config: RemoteJobConfig,
    record: dict[str, Any],
) -> None:
    if record.get("state") != "accepted":
        return
    try:
        receipt_value = remote_lifecycle.receipt_from_submission_record(config, record)
    except Exception as exc:
        raise ComputeContractError(
            "remote reconciliation record does not match the prepared intent"
        ) from exc
    job_id = receipt_value.scheduler_id
    receipt_ref = _receipt_ref(intent)
    receipt = remote_lifecycle.receipt_dict(receipt_value)
    _write_bound_record(workspace / receipt_ref, receipt, "reconciled remote receipt")
    result = _result(
        intent,
        job_id=job_id,
        state="submitted",
        program_status="not_run",
        artifact_refs=[receipt_ref],
        control=_control_outcome(
            operation="submit",
            phase="reconciled",
            effect_outcome="succeeded",
            effect_attempted=True,
            retry_disposition="none",
            reconciliation_required=False,
            submission_id=config.submission_id,
            job_id=job_id,
        ),
        provenance={
            "profile": config.profile.name,
            "scheduler": config.profile.scheduler,
            "remote_dir": config.remote_dir,
            "receipt_ref": receipt_ref,
            "submission_id": config.submission_id,
            "reconciliation_source": "remote_submission_record",
        },
    )
    _write_control_reconciliation(workspace, intent, "submit", result)


def _load_prepared(
    root: str | Path,
    intent_id: str,
    expected_intent_digest: str | None = None,
) -> tuple[Path, dict[str, Any], dict[str, Any]]:
    if not intent_id.startswith("calc_") or any(char not in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-" for char in intent_id[5:]):
        raise ComputeContractError("invalid intent_id")
    workspace = _workspace_root(root)
    matches = list((workspace / "acts").glob(f"*/attempts/{intent_id}/prepared.json"))
    if len(matches) != 1:
        raise ComputeContractError(f"expected exactly one prepared calculation for {intent_id}; found {len(matches)}")
    prepared = _read_object(matches[0], "prepared calculation")
    intent_ref = prepared.get("intent_ref")
    if not isinstance(intent_ref, str):
        raise ComputeContractError("prepared calculation has no intent_ref")
    intent = _read_object(workspace / _workspace_ref(workspace, intent_ref, read=True), "calculation intent")
    _validate_intent(intent)
    _require_expected_intent_digest(intent, expected_intent_digest)
    if sha256_json(intent) != prepared.get("intent_digest"):
        raise ComputeContractError(f"calculation intent digest mismatch: {intent_id}")
    if intent.get("intent_id") != intent_id or intent.get("act_id") != prepared.get("act_id"):
        raise ComputeContractError("prepared calculation scope does not match its intent")
    if prepared.get("schema_version") != "ts-compute-prepared/1" or prepared.get("intent_id") != intent_id:
        raise ComputeContractError("prepared calculation metadata is invalid")
    expected_task = asdict(
        _prepared_task_for_intent(workspace, intent, verify_inputs=False)
    )
    if prepared.get("prepared_task") != expected_task:
        raise ComputeContractError("prepared backend metadata does not match the calculation intent")
    expected_policy = _expected_prepared_execution_policy(workspace, intent)
    if prepared.get("execution_policy") != expected_policy:
        raise ComputeContractError("prepared execution policy does not match the calculation intent")
    if expected_policy["kind"] == "remote":
        _require_unique_remote_basenames(expected_task["expected_artifacts"])
        _remote_stdout_name(expected_task)
    return workspace, intent, prepared


def _workspace_root(root: str | Path) -> Path:
    workspace = Path(root).expanduser().resolve()
    workspace_doc = workspace / "workspace.json"
    if not workspace_doc.is_file() or not (workspace / "research_acts.json").is_file() or not (workspace / "acts").is_dir():
        raise ComputeContractError(f"not an initialized v4 TS workspace: {workspace}")
    if read_json(workspace_doc).get("schema_version") != "ts-workspace/4":
        raise ComputeContractError(f"unsupported TS workspace protocol: {workspace}")
    return workspace


def _intent_source(workspace: Path, value: str | Path) -> tuple[Path, str]:
    source = Path(value).expanduser()
    if source.is_absolute():
        lexical = Path(os.path.abspath(source))
        try:
            ref = lexical.relative_to(workspace.resolve(strict=True)).as_posix()
        except (OSError, ValueError) as exc:
            raise ComputeContractError("calculation intent file must be inside the TS workspace") from exc
        resolved = lexical.resolve(strict=True)
        try:
            resolved.relative_to(workspace.resolve(strict=True))
        except ValueError as exc:
            raise ComputeContractError("calculation intent file must be inside the TS workspace") from exc
    else:
        ref = _workspace_ref(workspace, source.as_posix(), read=True)
        resolved = (workspace / ref).resolve(strict=True)
    parts = PurePosixPath(ref).parts
    generated_source = (
        len(parts) == 5
        and parts[0] == "acts"
        and parts[2] == "attempts"
        and parts[4] == "intent.json"
        and parts[3].startswith("calc_")
    )
    if not generated_source:
        raise ComputeContractError("calculation intent file must be a Kernel-generated ResearchAct attempt intent")
    current = workspace
    for part in parts:
        current = current / part
        if current.is_symlink():
            raise ComputeContractError(f"calculation intent path contains a symbolic link: {ref}")
    return resolved, ref


def _require_request_scope(intent: dict[str, Any], act_id: str, backend: str) -> None:
    if intent.get("act_id") != act_id:
        raise ComputeContractError(
            f"compute request act_id does not match calculation intent: {act_id} != {intent.get('act_id')}"
        )
    if intent.get("backend") != backend:
        raise ComputeContractError(
            f"compute request backend does not match calculation intent: {backend} != {intent.get('backend')}"
        )


def _require_expected_intent_digest(intent: dict[str, Any], expected: str | None) -> None:
    if expected is not None and sha256_json(intent) != expected:
        raise ComputeContractError("calculation intent changed after compute preflight")


def _load_act(workspace: Path, act_id: str) -> dict[str, Any]:
    registry = _read_object(workspace / "research_acts.json", "ResearchAct registry")
    if registry.get("schema_version") != "ts-research-act-registry/2":
        raise ComputeContractError("invalid ResearchAct registry")
    matches = [
        item
        for item in registry.get("acts", [])
        if isinstance(item, dict) and item.get("act_id") == act_id
    ]
    if len(matches) != 1:
        raise ComputeContractError(f"unknown ResearchAct: {act_id}")
    return matches[0]


def _validate_intent(intent: dict[str, Any]) -> None:
    schema_version = intent.get("schema_version")
    if schema_version != "ts-calculation-intent/4":
        raise ComputeContractError(f"unsupported calculation intent schema_version: {schema_version}")
    validate_compute_contract(INTENT_SCHEMA, intent)


def _validate_intent_act_scope(workspace: Path, intent: dict[str, Any], act: dict[str, Any]) -> None:
    if act.get("schema_version") != "ts-research-act/2":
        raise ComputeContractError("calculations require a ts-research-act/2 owner")
    if act.get("status") != "open":
        raise ComputeContractError("calculations require an open ResearchAct")
    if intent.get("act_id") != act.get("act_id"):
        raise ComputeContractError("calculation intent owner does not match its ResearchAct")

    if intent.get("attempt_kind") != "recalculation":
        return
    recalculation = intent.get("recalculation_ref")
    source_act = recalculation.get("source_act") if isinstance(recalculation, dict) else None
    try:
        _load_act(workspace, str(source_act))
    except ComputeContractError as exc:
        raise ComputeContractError(f"recalculation_ref.source_act does not exist: {source_act}")
    source_intent = recalculation.get("source_intent_id")
    if source_intent is not None:
        source_matches = [
            *list((workspace / "acts" / source_act).glob(f"attempts/{source_intent}/intent.json")),
        ]
        if len(source_matches) != 1:
            raise ComputeContractError(
                f"recalculation_ref.source_intent_id must identify one local source attempt: {source_intent}"
            )


def _workspace_ref(workspace: Path, value: str, *, read: bool) -> str:
    text = str(value).replace("\\", "/").lstrip("@")
    if PurePosixPath(text).is_absolute():
        raise ComputeContractError(f"workspace path must be relative: {value}")
    normalized = posixpath.normpath(text)
    if normalized in {"", ".", ".."} or normalized.startswith("../"):
        raise ComputeContractError(f"invalid workspace path: {value}")
    path = (workspace / normalized).resolve()
    try:
        path.relative_to(workspace)
    except ValueError as exc:
        raise ComputeContractError(f"workspace path escapes root: {value}") from exc
    if read:
        if not path.is_file():
            raise ComputeContractError(f"workspace input does not exist: {normalized}")
        try:
            path.resolve(strict=True).relative_to(workspace.resolve(strict=True))
        except ValueError as exc:
            raise ComputeContractError(f"workspace input symlink escapes root: {normalized}") from exc
    return normalized


def _require_attempt_output_ref(act_id: str, intent_id: str, ref: str) -> None:
    prefix = f"acts/{act_id}/attempts/{intent_id}/outputs/"
    if not ref.startswith(prefix) or ref == prefix:
        raise ComputeContractError(f"calculation output must be under {prefix}")


def _require_calculation_output_ref(intent: dict[str, Any], ref: str) -> None:
    act_id = str(intent["act_id"])
    _require_attempt_output_ref(act_id, str(intent["intent_id"]), ref)


def _require_compute_input_ref(ref: str) -> None:
    parts = PurePosixPath(ref).parts
    if len(parts) >= 2 and parts[0] == "inputs":
        return
    if len(parts) >= 4 and parts[0] == "acts" and parts[2] in {"inputs", "outputs"}:
        return
    if len(parts) >= 6 and parts[0] == "acts" and parts[2] == "attempts" and parts[4] == "outputs":
        return
    raise ComputeContractError("calculation inputs must come from workspace or ResearchAct inputs/outputs")


def _record_refs(act_id: str, intent_id: str) -> tuple[str, str]:
    base = f"acts/{act_id}/attempts/{intent_id}"
    return f"{base}/intent.json", f"{base}/prepared.json"


def _runtime_refs(act_id: str, intent_id: str) -> tuple[str, str, str]:
    base = f"acts/{act_id}/attempts/{intent_id}"
    return base, f"{base}/status.json", f"{base}/outputs"


def _control_result_ref(
    intent: dict[str, Any],
    operation: str,
    attempt: int = 1,
) -> str:
    if operation not in {"submit", "cancel"}:
        raise ComputeContractError(f"unsupported durable control operation: {operation}")
    base, _, _ = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    suffix = f"{operation}_result.json" if attempt == 1 else f"{operation}_attempt_{attempt:04d}_result.json"
    return f"{base}/{suffix}"


def _control_guard_ref(
    intent: dict[str, Any],
    operation: str,
    attempt: int = 1,
) -> str:
    if operation not in {"submit", "cancel"}:
        raise ComputeContractError(f"unsupported durable control operation: {operation}")
    base, _, _ = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    suffix = f"{operation}_guard.json" if attempt == 1 else f"{operation}_attempt_{attempt:04d}_guard.json"
    return f"{base}/{suffix}"


def _control_reconciliation_ref(intent: dict[str, Any], operation: str) -> str:
    if operation not in {"submit", "cancel"}:
        raise ComputeContractError(f"unsupported durable control operation: {operation}")
    base, _, _ = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    return f"{base}/{operation}_reconciliation.json"


def _write_once(path: Path, value: dict[str, Any], identity: str) -> None:
    if path.exists():
        if _read_object(path, identity) != value:
            raise ComputeContractError(f"{identity} already exists with different content: {value.get(identity)}")
        return
    write_json(path, value)


def _write_text_once(path: Path, value: str, label: str) -> None:
    if path.exists() or path.is_symlink():
        if not path.is_file() or path.is_symlink() or path.read_text(encoding="utf-8") != value:
            raise ComputeContractError(f"{label} already exists with different content: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f"{path.name}.tmp")
    temporary.write_text(value, encoding="utf-8")
    temporary.replace(path)


def _write_bound_record(path: Path, value: dict[str, Any], label: str) -> None:
    if path.exists() or path.is_symlink():
        if path.is_symlink() or _read_object(path, label) != value:
            raise ComputeContractError(f"{label} already exists with different content: {path}")
        return
    write_json(path, value)


def _read_local_status(workspace: Path, intent: dict[str, Any]) -> dict[str, Any] | None:
    _, status_ref, _ = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    path = workspace / status_ref
    if path.is_symlink():
        raise ComputeContractError("calculation status cannot be a symbolic link")
    if not path.is_file():
        return None
    status = _read_object(path, "calculation status")
    _validate_bound_result(intent, status, "calculation status")
    return status


def _write_status(workspace: Path, intent: dict[str, Any], result: dict[str, Any]) -> None:
    _validate_bound_result(intent, result, "calculation status")
    _, status_ref, _ = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    write_json(workspace / status_ref, result)


def _read_control_result(
    workspace: Path,
    intent: dict[str, Any],
    operation: str,
) -> dict[str, Any] | None:
    reconciliation_path = workspace / _control_reconciliation_ref(intent, operation)
    if reconciliation_path.is_symlink():
        raise ComputeContractError(f"{operation} reconciliation cannot be a symbolic link")
    if reconciliation_path.is_file():
        result = _read_object(reconciliation_path, f"{operation} reconciliation")
        _validate_bound_result(intent, result, f"{operation} reconciliation")
        return result
    attempt = _latest_completed_control_attempt(workspace, intent, operation)
    if attempt is None:
        return None
    path = workspace / _control_result_ref(intent, operation, attempt)
    if path.is_symlink():
        raise ComputeContractError(f"{operation} control result cannot be a symbolic link")
    if not path.is_file():
        return None
    result = _read_object(path, f"{operation} control result")
    _validate_bound_result(intent, result, f"{operation} control result")
    return result


def _read_control_guard(
    workspace: Path,
    intent: dict[str, Any],
    operation: str,
) -> dict[str, Any] | None:
    attempt = _latest_control_attempt(workspace, intent, operation)
    if attempt is None:
        return None
    path = workspace / _control_guard_ref(intent, operation, attempt)
    if path.is_symlink():
        raise ComputeContractError(f"{operation} control guard cannot be a symbolic link")
    if not path.is_file():
        return None
    guard = _read_object(path, f"{operation} control guard")
    if (
        guard.get("schema_version") != "ts-compute-control-guard/1"
        or guard.get("operation") != operation
        or guard.get("attempt", 1) != attempt
        or guard.get("intent_id") != intent.get("intent_id")
        or guard.get("act_id") != intent.get("act_id")
        or guard.get("intent_digest") != sha256_json(intent)
    ):
        raise ComputeContractError(f"{operation} control guard is not bound to the prepared intent")
    return guard


def _claim_control(workspace: Path, intent: dict[str, Any], operation: str) -> int:
    latest = _latest_control_attempt(workspace, intent, operation)
    if latest is not None:
        pending = workspace / _control_guard_ref(intent, operation, latest)
        completed = workspace / _control_result_ref(intent, operation, latest)
        if pending.is_file() and not pending.is_symlink() and not completed.is_file():
            raise ComputeContractError(
                f"{operation} already has a valid durable control guard; automatic replay is forbidden"
            )
    attempt = 1 if latest is None else latest + 1
    path = workspace / _control_guard_ref(intent, operation, attempt)
    path.parent.mkdir(parents=True, exist_ok=True)
    guard = {
        "schema_version": "ts-compute-control-guard/1",
        "operation": operation,
        "attempt": attempt,
        "intent_id": intent["intent_id"],
        "act_id": intent["act_id"],
        "intent_digest": sha256_json(intent),
        "started_at": now_iso(),
    }
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    try:
        descriptor = os.open(path, flags, 0o600)
    except FileExistsError as exc:
        existing = _read_control_guard(workspace, intent, operation)
        state = "valid" if existing is not None else "invalid"
        raise ComputeContractError(
            f"{operation} already has a {state} durable control guard; automatic replay is forbidden"
        ) from exc
    try:
        payload = (json.dumps(guard, indent=2, sort_keys=True) + "\n").encode("utf-8")
        view = memoryview(payload)
        while view:
            written = os.write(descriptor, view)
            view = view[written:]
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    directory_flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
    directory_descriptor = os.open(path.parent, directory_flags)
    try:
        os.fsync(directory_descriptor)
    finally:
        os.close(directory_descriptor)
    return attempt


def _write_control_result(
    workspace: Path,
    intent: dict[str, Any],
    operation: str,
    result: dict[str, Any],
    attempt: int = 1,
) -> None:
    _validate_bound_result(intent, result, f"{operation} control result")
    _write_bound_record(
        workspace / _control_result_ref(intent, operation, attempt),
        result,
        f"{operation} control result",
    )


def _write_control_reconciliation(
    workspace: Path,
    intent: dict[str, Any],
    operation: str,
    result: dict[str, Any],
) -> None:
    _validate_bound_result(intent, result, f"{operation} reconciliation")
    _write_bound_record(
        workspace / _control_reconciliation_ref(intent, operation),
        result,
        f"{operation} reconciliation",
    )


def _latest_control_attempt(
    workspace: Path,
    intent: dict[str, Any],
    operation: str,
) -> int | None:
    base, _, _ = _runtime_refs(
        str(intent["act_id"]),
        str(intent["intent_id"]),
    )
    root = workspace / base
    attempts: set[int] = set()
    for kind in ("guard", "result"):
        initial = root / f"{operation}_{kind}.json"
        if initial.exists() or initial.is_symlink():
            attempts.add(1)
        prefix = f"{operation}_attempt_"
        suffix = f"_{kind}.json"
        for path in root.glob(f"{prefix}*{suffix}"):
            token = path.name.removeprefix(prefix).removesuffix(suffix)
            if len(token) != 4 or not token.isdigit() or int(token) < 2:
                raise ComputeContractError(f"invalid {operation} control attempt path: {path}")
            attempts.add(int(token))
    return max(attempts) if attempts else None


def _latest_completed_control_attempt(
    workspace: Path,
    intent: dict[str, Any],
    operation: str,
) -> int | None:
    latest = _latest_control_attempt(workspace, intent, operation)
    if latest is None:
        return None
    for attempt in range(latest, 0, -1):
        path = workspace / _control_result_ref(intent, operation, attempt)
        if path.is_file() and not path.is_symlink():
            return attempt
    return None


def _control_allows_same_submission_retry(result: dict[str, Any]) -> bool:
    control = result.get("control")
    return (
        isinstance(control, dict)
        and control.get("operation") == "submit"
        and control.get("effect_outcome") == "failed"
        and control.get("effect_attempted") is False
        and control.get("retry_disposition") == "retry_same_submission"
        and control.get("reconciliation_required") is False
    )


def _validate_bound_result(intent: dict[str, Any], result: dict[str, Any], label: str) -> None:
    validate_compute_contract(RESULT_SCHEMA, result)
    provenance = result.get("provenance")
    if (
        result.get("intent_id") != intent.get("intent_id")
        or result.get("act_id") != intent.get("act_id")
        or not isinstance(provenance, dict)
        or provenance.get("intent_digest") != sha256_json(intent)
        or provenance.get("backend") != intent.get("backend")
    ):
        raise ComputeContractError(f"{label} is not bound to the prepared calculation intent")


def _write_result(workspace: Path, intent: dict[str, Any], result: dict[str, Any]) -> None:
    _, _, output_ref = _runtime_refs(str(intent["act_id"]), str(intent["intent_id"]))
    write_json(workspace / output_ref / "calculation_result.json", result)


def _result(
    intent: dict[str, Any],
    *,
    job_id: str | None = None,
    state: str,
    program_status: str,
    exit_status: int | None = None,
    artifact_refs: list[str] | None = None,
    parser_facts: dict[str, Any] | None = None,
    error_class: str | None = None,
    control: dict[str, Any] | None = None,
    provenance: dict[str, Any] | None = None,
) -> dict[str, Any]:
    result = {
        "schema_version": "ts-calculation-result/2",
        "job_id": job_id,
        "intent_id": intent["intent_id"],
        "act_id": intent["act_id"],
        "state": state,
        "program_status": program_status,
        "exit_status": exit_status,
        "artifact_refs": list(dict.fromkeys(artifact_refs or [])),
        "parser_facts": parser_facts or {},
        "error_class": error_class,
        "provenance": {
            "backend": intent["backend"],
            "intent_digest": sha256_json(intent),
            "intent_schema": intent["schema_version"],
            "attempt_kind": intent["attempt_kind"],
            "recalculation_ref": intent.get("recalculation_ref"),
            "remote_authority": "execution_mirror" if intent.get("execution_target", {}).get("kind") == "remote" else None,
            **(provenance or {}),
        },
    }
    if control is not None:
        result["control"] = control
    validate_compute_contract(RESULT_SCHEMA, result)
    return result


def _control_outcome(
    *,
    operation: str,
    phase: str,
    effect_outcome: str,
    effect_attempted: bool,
    retry_disposition: str,
    reconciliation_required: bool,
    submission_id: str | None,
    job_id: str | None,
) -> dict[str, Any]:
    return {
        "schema_version": "ts-control-outcome/1",
        "operation": operation,
        "phase": phase,
        "effect_outcome": effect_outcome,
        "effect_attempted": effect_attempted,
        "retry_disposition": retry_disposition,
        "reconciliation_required": reconciliation_required,
        "submission_id": submission_id,
        "job_id": job_id,
    }


def _require_cancellable_status(status: dict[str, Any]) -> None:
    state = status.get("state")
    if state not in {"submitted", "queued", "running", "unknown"}:
        raise ComputeContractError(f"cancel requires an active or unresolved remote job; current state is {state}")


def _require_matching_job_id(
    submitted: dict[str, Any],
    observed_job_id: str | None,
    label: str,
) -> None:
    submitted_job_id = submitted.get("job_id")
    if not isinstance(submitted_job_id, str) or not submitted_job_id:
        raise ComputeContractError(f"{label} requires a known submitted scheduler job_id")
    if observed_job_id != submitted_job_id:
        raise ComputeContractError(f"{label} job_id does not match the durable submit result")


def _collection_program_status(
    workspace: Path,
    intent: dict[str, Any],
    prepared: dict[str, Any],
    policy: dict[str, Any],
) -> str:
    """Validate the immutable submission binding without consulting the scheduler."""

    submitted = _read_control_result(workspace, intent, "submit")
    if submitted is None or submitted.get("state") != "submitted":
        raise ComputeContractError("collect requires a durable successful submit result")
    remote_dir = str(policy["remote_dir"])
    provenance = submitted.get("provenance")
    if not isinstance(provenance, dict) or any(
        provenance.get(key) != expected
        for key, expected in {
            "profile": policy["profile"],
            "scheduler": "torque",
            "remote_dir": remote_dir,
        }.items()
    ):
        raise ComputeContractError("collect submit result does not match the prepared remote target")

    receipt_ref = _receipt_ref(intent)
    if provenance.get("receipt_ref") != receipt_ref or receipt_ref not in submitted.get("artifact_refs", []):
        raise ComputeContractError("collect submit result is not bound to its durable receipt")
    receipt_path = workspace / receipt_ref
    if receipt_path.is_symlink():
        raise ComputeContractError("collect receipt cannot be a symbolic link")
    receipt = _read_object(receipt_path, "remote receipt")
    remote_config = _remote_job_config(workspace, intent, prepared)
    if any(
        receipt.get(key) != expected
        for key, expected in {
            "schema_version": "ts-remote-receipt/1",
            "act_id": intent["act_id"],
            "intent_id": intent["intent_id"],
            "intent_digest": sha256_json(intent),
            "profile": policy["profile"],
            "scheduler": "torque",
            "remote_dir": remote_dir,
            "scheduler_id": submitted.get("job_id"),
            "submission_id": _remote_submission_id(
                str(policy["workspace_id"]),
                str(intent["intent_id"]),
            ),
            "script_sha256": remote_lifecycle.submission_script_digest(remote_config),
        }.items()
    ):
        raise ComputeContractError("collect receipt does not match the durable submit result")
    manifest = receipt.get("expected_artifacts")
    expected_names = _expected_remote_names(prepared)
    if not isinstance(manifest, list) or any(not isinstance(item, str) for item in manifest):
        raise ComputeContractError("collect receipt artifact manifest must be a string array")
    if manifest != expected_names:
        raise ComputeContractError("collect receipt artifact manifest does not match prepared artifacts")
    if provenance.get("submission_id") != receipt["submission_id"]:
        raise ComputeContractError("collect submit result has a mismatched submission_id")

    status = _read_local_status(workspace, intent)
    if status is None:
        return "not_run"
    value = str(status.get("program_status", "not_run"))
    return value if value in {"completed", "failed", "stopped"} else "not_run"


def _require_unique_remote_basenames(refs: list[str]) -> None:
    names = [Path(ref).name for ref in refs]
    if len(names) != len(set(names)):
        raise ComputeContractError("expected remote artifacts have colliding basenames")


def _read_object(path: Path, label: str) -> dict[str, Any]:
    if not path.is_file():
        raise ComputeContractError(f"{label} file does not exist: {path}")
    value = read_json(path)
    if not isinstance(value, dict):
        raise ComputeContractError(f"{label} must be a JSON object: {path}")
    return value


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()
