#!/usr/bin/env python3
"""Generate command transports, model parameter types and review fixtures.

Only contracts/commands is authored. Model schemas stay distinct from application
commands: trusted session and receipt fields never become model parameters.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'contracts/commands'
HEADER = '// Generated by tools/generate_contracts.py. Do not edit independently.\n'


def encoded(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + '\n'


def resolve(value, documents, trail=()):
    if isinstance(value, list):
        return [resolve(item, documents, trail) for item in value]
    if not isinstance(value, dict):
        return value
    if '$ref' in value:
        reference = value['$ref']
        if reference in trail:
            raise ValueError('recursive contract reference: ' + reference)
        document, pointer = reference.split('#/', 1)
        selected = documents[document]
        for part in pointer.split('/'):
            selected = selected[part.replace('~1', '/').replace('~0', '~')]
        return {**resolve(selected, documents, (*trail, reference)),
                **{key: resolve(item, documents, trail) for key, item in value.items() if key != '$ref'}}
    return {key: resolve(item, documents, trail) for key, item in value.items()}


def ts_type(schema, depth=0):
    if schema is True:
        return 'unknown'
    if schema is False:
        return 'never'
    if schema.get('x-typescript-type') == 'JsonValue':
        return 'JsonValue'
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    branches = schema.get('anyOf', schema.get('oneOf'))
    if branches and 'properties' not in schema:
        return ' | '.join(ts_type(value, depth) for value in branches)
    kind = schema.get('type')
    if isinstance(kind, list):
        return ' | '.join(ts_type({**schema, 'type': value}, depth) for value in kind)
    if kind == 'array':
        return 'Array<' + ts_type(schema.get('items', {}), depth) + '>'
    if kind == 'object' or 'properties' in schema:
        required = set(schema.get('required', []))
        fields = [('  ' * (depth + 1)) + json.dumps(key) + ('' if key in required else '?') + ': ' + ts_type(value, depth + 1) + ';'
                  for key, value in schema.get('properties', {}).items()]
        if not fields:
            patterns = list(schema.get('patternProperties', {}).values())
            if patterns:
                return 'Record<string, ' + ' | '.join(ts_type(item, depth) for item in patterns) + '>'
            additional = schema.get('additionalProperties', True)
            return 'Record<string, never>' if additional is False else 'Record<string, ' + ts_type(additional, depth) + '>'
        if schema.get('additionalProperties', True) is not False:
            fields.append('  ' * (depth + 1) + '[key: string]: unknown;')
        return '{\n' + '\n'.join(fields) + '\n' + '  ' * depth + '}'
    return {'integer': 'number', 'number': 'number', 'boolean': 'boolean', 'null': 'null', 'string': 'string'}.get(kind, 'unknown')


def outputs():
    documents = {path.name: json.loads(path.read_text()) for path in SOURCE.glob('*.json')}
    if documents['results.json']['schema_version'] != 'coragent-command-results/1':
        raise ValueError('invalid command result schemas')
    commands, examples = [], []
    for name in ('research', 'jobs', 'artifacts'):
        source = documents[name + '.json']
        if source['schema_version'] != 'coragent-command-source/1':
            raise ValueError('invalid command source: ' + name)
        for definition in source['commands']:
            schema = resolve(definition['schema'], documents)
            if schema.get('type') != 'object' or schema.get('additionalProperties') is not False:
                raise ValueError('commands require closed parameter objects')
            required = schema.get('required', [])
            if set(required) - schema['properties'].keys():
                raise ValueError('required command field is undeclared')
            result = resolve(definition['result'], documents)
            commands.append({**{key: value for key, value in definition.items() if key not in {'schema', 'examples', 'result'}},
                             'allowed': list(schema['properties']), 'required': required, 'schema': schema,
                             'result': result})
            examples.extend({'command': definition['id'], 'params': value} for value in definition['examples'])
    if len({item['id'] for item in commands}) != len(commands):
        raise ValueError('duplicate command identity')
    slash = documents['slash.json']['commands']
    catalog = {'schema_version': 'coragent-command-catalog/1', 'commands': commands, 'slash_commands': slash}
    shared = documents['shared.json']
    if shared['schema_version'] != 'coragent-command-schemas/1':
        raise ValueError('invalid shared command schemas')
    tools = resolve(shared['tools'], documents)
    tool_types = HEADER + 'export interface ToolParameters {\n' + '\n'.join(
        '  ' + key + ': ' + ts_type(schema, 1) + ';' for key, schema in tools.items()) + '\n}\n'
    command_types = HEADER + 'export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n'
    command_types += 'export interface CommandParameters {\n' + '\n'.join(
        '  ' + json.dumps(item['id']) + ': ' + ts_type(item['schema'], 1) + ';' for item in commands) + '\n}\n\n'
    command_types += 'export interface CommandResults {\n' + '\n'.join(
        '  ' + json.dumps(item['id']) + ': ' + ts_type(item['result'], 1) + ';' for item in commands) + '\n}\n\n'
    command_types += '''export type CommandId = keyof CommandParameters;
export interface CommandInvocation {
  readonly command: CommandId;
  readonly params: Readonly<Record<string, unknown>>;
}
export interface CommandTransportInvocation extends CommandInvocation {
  readonly root: string;
  readonly signal?: AbortSignal;
}
export const COMMAND_DEFINITIONS: Readonly<Record<CommandId, {
  readonly id: CommandId;
  readonly domain: "research" | "runtime";
  readonly effect?: "read" | "write";
  readonly required: readonly string[];
  readonly allowed: readonly string[];
  readonly schema: Readonly<Record<string, unknown>>;
  readonly result: Readonly<Record<string, unknown>>;
}>>;
export const COMMAND_IDS: readonly CommandId[];
export const SLASH_COMMAND_DEFINITIONS: Readonly<Record<string, {
  readonly name: string;
  readonly description: string;
  readonly usage: string;
  readonly completions: readonly string[];
}>>;
export const SLASH_COMMAND_NAMES: readonly string[];
export function createCommandService(transport: {
  execute(invocation: CommandTransportInvocation): Promise<unknown>;
}): {
  execute<C extends CommandId>(command: C, root: string, params?: Record<string, unknown>, signal?: AbortSignal): Promise<CommandResults[C]>;
};
export function validateCommandInvocation(command: string, params?: Record<string, unknown>): CommandInvocation;
export function commandArguments(command: string, params?: Record<string, unknown>): string[];
export function parseSlashCommand(name: string, input?: string): CommandInvocation | {
  readonly command: "client.sys-prompt" | "client.resume" | "client.quit" | "client.usage" | "client.monitor";
  readonly params: Readonly<Record<string, unknown>>;
};
export function slashCompletions(name: string, prefix?: string): Array<{ value: string; label: string; description?: string }> | null;
'''
    index = ['<!-- Generated by tools/generate_contracts.py. -->', '# Application commands', '',
             'Model parameters are declared separately in shared.json. Session identity and read receipts belong to application commands.', '',
             'results.json declares JSON response DTOs, including read variants and unsuccessful Job dispatch replies. '
             'It generates CommandResults and command-specific transport return types. '
             'Response schemas are checked against actual API replies in tests; production does not validate responses.', '',
             '| Command | Required parameters | Effect |', '| --- | --- | --- |']
    index.extend('| `' + item['id'] + '` | ' + ', '.join('`' + key + '`' for key in item['required']) + ' | ' + item.get('effect', '') + ' |' for item in commands)
    return {
        ROOT / 'backend/src/research_agent/application/command_catalog.json': encoded(catalog),
        ROOT / 'apps/agent/tools/command-catalog.json': encoded(catalog),
        ROOT / 'apps/agent/tools/parameters.d.mts': tool_types,
        ROOT / 'apps/agent/tools/commands.d.mts': command_types,
        ROOT / 'contracts/generated/command-fixtures.json': encoded({'schema_version': 'coragent-command-fixtures/1', 'cases': examples}),
        ROOT / 'contracts/commands/README.md': '\n'.join(index) + '\n',
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        parser.exit(1, 'Generated contracts are stale: ' + ', '.join(stale) + '\n')


if __name__ == '__main__':
    main()
