#!/usr/bin/env python3
"""Generate npm's release boundary from the source ownership declaration."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    layout = json.loads((ROOT / "config/source-layout.json").read_text())
    path = ROOT / "package.json"
    package = json.loads(path.read_text())
    package["files"] = [*layout["roots"], *layout["files"], *layout["generated"], *("!" + value for value in layout["exclude"])]
    outputs = {path: json.dumps(package, indent=2, ensure_ascii=False) + "\n"}
    identity = json.loads((ROOT / "config/identity.json").read_text())
    protocol_path = ROOT / "backend/src/research_agent/foundation/protocol.json"
    protocol = json.loads(protocol_path.read_text())
    for key in ("host_protocol", "link_protocol", "host_token_prefix", "device_token_prefix"):
        protocol[key] = identity[key]
    outputs[protocol_path] = json.dumps(protocol, indent=2) + "\n"
    outputs[ROOT / "packages/link/identity.mjs"] = (
        "// Generated by tools/layout.py from config/identity.json.\n"
        + "".join(f"export const {key.upper()} = {json.dumps(identity[key])};\n"
                  for key in ("link_protocol", "host_token_prefix", "device_token_prefix"))
    )
    for path, generated in outputs.items():
        if args.check:
            if not path.is_file() or generated != path.read_text():
                raise SystemExit(f"generated layout is stale: {path.relative_to(ROOT)}; run tools/layout.py")
        else:
            path.write_text(generated)


if __name__ == "__main__":
    main()
