#!/usr/bin/env python3
"""Set or check the product version; dependencies and protocols have their own versions."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = re.compile(r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-rc\.(0|[1-9]\d*))?")
MANIFESTS = ("package.json", "packages/link/package.json", "services/relay/package.json",
             "components/ts-web/package.json", "domains/chemical/package.json")
LOCKS = ("package-lock.json", "services/relay/package-lock.json")


def python_version(version: str) -> str:
    if not VERSION.fullmatch(version):
        raise ValueError("product version must be major.minor.patch or major.minor.patch-rc.N")
    return version.replace("-rc.", "rc")


def generated(root: Path, version: str) -> dict[Path, str]:
    normalized = python_version(version)
    output = {}
    for relative in MANIFESTS:
        path = root / relative
        value = json.loads(path.read_text())
        value["version"] = version
        output[path] = json.dumps(value, indent=2, ensure_ascii=False) + "\n"
    for relative in LOCKS:
        path = root / relative
        value = json.loads(path.read_text())
        package = json.loads((path.parent / "package.json").read_text())
        value.update(name=package["name"], version=version)
        value["packages"][""].update(name=package["name"], version=version)
        output[path] = json.dumps(value, indent=2, ensure_ascii=False) + "\n"
    output[root / "backend/src/research_agent/_version.py"] = (
        '# Generated by tools/version.py from package.json.\n'
        f'__version__ = "{normalized}"\n'
    )
    return output


def check(root: Path = ROOT) -> None:
    version = json.loads((root / "package.json").read_text())["version"]
    stale = [str(path.relative_to(root)) for path, content in generated(root, version).items()
             if path.read_text() != content]
    if stale:
        raise ValueError("product versions are stale: " + ", ".join(stale))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("check")
    commands.add_parser("set").add_argument("version")
    args = parser.parse_args()
    if args.command == "check":
        check()
    else:
        for path, content in generated(ROOT, args.version).items():
            path.write_text(content)


if __name__ == "__main__":
    main()
