// Generated by tools/generate_contracts.py. Do not edit independently.
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface CommandParameters {
  "research.read": {
    "ref"?: string | null;
    "offset"?: number;
    "limit"?: number;
    "session_id"?: string | null;
    "event_ids"?: Array<string>;
    "focus_node_ids"?: Array<string>;
    "field"?: "goal" | "title" | "proposal" | "plan" | "progress" | "status" | "assessment_ref" | "relations" | null;
  };
  "research.search": {
    "query"?: string;
    "origin"?: "user" | "runtime" | "agent" | null;
    "node_id"?: string | null;
    "kind"?: string | null;
    "after_sequence"?: number;
    "offset"?: number;
    "limit"?: number;
    "session_id"?: string | null;
  };
  "research.create": {
    "goal": string;
    "title"?: string | null;
    "proposal"?: string | null;
    "plan"?: string | null;
    "source_refs"?: Array<string>;
    "input_refs"?: Array<string>;
    "relations"?: Array<Record<string, unknown>>;
    "session_id"?: string | null;
    "request_id"?: string;
    "read_basis"?: string | null;
    "subjects"?: Record<string, string>;
  };
  "research.update": {
    "node_id": string;
    "note": string;
    "goal"?: string;
    "title"?: string | null;
    "proposal"?: string | null;
    "plan"?: string | null;
    "progress"?: string | null;
    "status"?: "open" | "paused" | "closed";
    "assessment_ref"?: string | null;
    "add_relations"?: Array<Record<string, unknown>>;
    "remove_relations"?: Array<string>;
    "session_id"?: string | null;
    "request_id"?: string;
    "read_basis"?: string | null;
    "subjects"?: Record<string, string>;
  };
  "research.result": {
    "node_id": string;
    "conclusion": string;
    "summary"?: string | null;
    "observation"?: string | null;
    "limitations"?: string | null;
    "inputs"?: Array<string>;
    "evidence_refs"?: Array<string>;
    "files"?: Array<Record<string, unknown>>;
    "supersedes"?: string | null;
    "as_assessment"?: boolean;
    "session_id"?: string | null;
    "request_id"?: string;
    "read_basis"?: string | null;
    "subjects"?: Record<string, string>;
    "check_refs"?: Array<string>;
    "progress"?: string;
  };
  "research.source": {
    "session_id": string | null;
    "message_id": string;
    "text": string;
  };
  "research.observe": {
    "session_id"?: string | null;
    "read_basis": string | null;
  };
  "job.start": {
    "job_id"?: string;
    "request_id"?: string;
    "command"?: Array<string>;
    "cwd"?: string | null;
    "inputs"?: Array<unknown>;
    "outputs"?: Array<Record<string, unknown>>;
    "environment"?: Record<string, string> | string | null;
    "env"?: Record<string, string> | null;
    "timeout_seconds"?: number | null;
    "metadata"?: Record<string, unknown> | null;
    "workspace_id"?: string;
    "work_id"?: string;
    "platform"?: string;
    "execution_target"?: Record<string, unknown>;
    "session_id"?: string | null;
    "validator_id"?: string;
    "input_artifact_ids"?: Array<string>;
    "repeat"?: {
      "predecessor_job_id": string;
      "reason": string;
      "budget": string;
    };
    "prepared_ref"?: string;
    "validator_version"?: string;
    "request_file"?: string;
    "request_sha256"?: string | null;
    "node_id"?: string;
  };
  "job.status": {
    "job_id"?: string;
    "event_id"?: string;
  };
  "job.collect": {
    "job_id"?: string;
    "event_id"?: string;
  };
  "job.cancel": {
    "job_id"?: string;
    "event_id"?: string;
  };
  "job.probe": {
    "job_id"?: string;
    "request_id"?: string;
    "command"?: Array<string>;
    "cwd"?: string | null;
    "inputs"?: Array<unknown>;
    "outputs"?: Array<Record<string, unknown>>;
    "environment"?: Record<string, string> | string | null;
    "env"?: Record<string, string> | null;
    "timeout_seconds"?: number | null;
    "metadata"?: Record<string, unknown> | null;
    "workspace_id"?: string;
    "work_id"?: string;
    "platform"?: string;
    "execution_target"?: Record<string, unknown>;
  };
  "job.reconcile": {
    "job_id"?: string;
    "event_id"?: string;
  };
  "job.prepare": {
    "request_file": string;
  };
  "job.resolve_prepared": {
    "prepared_ref": string;
    "timeout_seconds"?: number | null;
    "repeat"?: {
      "predecessor_job_id": string;
      "reason": string;
      "budget": string;
    };
  };
  "job.monitor_assess": {
    "event_id": string;
    "session_id": string | null;
  };
  "artifact.register": {
    "artifact_id"?: string;
    "path"?: string;
    "job_id"?: string;
    "sha256"?: string;
    "media_type"?: string;
  };
  "artifact.create": {
    "artifact_id"?: string;
    "content"?: string | Array<number>;
    "name"?: string | null;
    "job_id"?: string;
    "sha256"?: string;
    "media_type"?: string;
  };
  "artifact.read": {
    "artifact_id"?: string;
    "offset"?: number;
    "limit"?: number;
    "artifact_ref"?: string;
  };
}

export interface CommandResults {
  "research.read": {
    "schema_version": "research-snapshot/2";
    "workspace_id": string;
    "sequence": number;
    "nodes": Array<{
      "schema_version"?: "research-node/1";
      "id": string;
      "workspace_id"?: string;
      "title": string;
      "goal": string;
      "proposal"?: string | null;
      "plan"?: string | null;
      "progress": string | null;
      "status": "open" | "paused" | "closed";
      "assessment_ref": string | null;
      "source_refs"?: Array<string>;
      "input_refs"?: Array<string>;
      "revision": number;
      "created_at"?: string;
      "updated_at"?: string;
      "author"?: {
        "session_id": string | null;
      };
      "read": {
        "ref": string;
      };
      "content_omitted"?: boolean;
      "ranking_reason"?: string;
      "recent_results"?: Array<{
        "id": string;
        "summary": string;
        "content_omitted": boolean;
        "read": {
          "ref": string;
        };
      }>;
      "subjects"?: Record<string, string>;
      "review_notices"?: Array<JsonValue>;
      "review_notice_count"?: number;
    }>;
    "tasks": Array<JsonValue>;
    "new_records": Array<JsonValue>;
    "running_jobs": Array<JsonValue>;
    "uncollected_jobs": Array<JsonValue>;
    "diagnostics": Array<JsonValue>;
    "events": Array<JsonValue>;
    "wake_events": {
      "requested": number;
      "included": number;
      "omitted": number;
    };
    "projection": {
      "pending": number;
      [key: string]: unknown;
    };
    "bounds": {
      "max_bytes": number;
      "omitted": Record<string, number>;
    };
    "read_more": JsonValue;
    "guidance": string;
    "read_basis": string;
    "snapshot_id": string;
  } | {
    "schema_version": "research-read/2";
    "ref": string;
    "text": string;
    "offset": number;
    "offset_unit": "unicode_characters";
    "total_characters": number;
    "next_offset": number | null;
    "node_id"?: string;
    "node_revision"?: number;
    "field"?: string;
    "value"?: JsonValue;
    "read_basis"?: string;
    "node"?: {
      "schema_version": "research-node/1";
      "id": string;
      "workspace_id": string;
      "title": string;
      "goal": string;
      "proposal": string | null;
      "plan": string | null;
      "progress": string | null;
      "status": "open" | "paused" | "closed";
      "assessment_ref": string | null;
      "source_refs": Array<string>;
      "input_refs": Array<string>;
      "revision": number;
      "created_at": string;
      "updated_at": string;
      "author": {
        "session_id": string | null;
      };
      "subjects"?: Record<string, string>;
    };
    "relations"?: Array<{
      "id": string;
      "source": string;
      "target": string;
      "kind": string;
      "reason": string;
      "origin": string;
      "basis_refs": Array<string>;
      "active": boolean;
      "created_at": string;
    }>;
    "results"?: Array<{
      "id": string;
      "node_id": string;
      "summary": string;
      "created_at": string;
      "supersedes": string | null;
      "content_digest": string;
    }>;
    "assessment"?: JsonValue;
    "result"?: {
      "schema_version": "research-result/1";
      "id": string;
      "workspace_id": string;
      "node_id": string;
      "summary": string;
      "summary_is_excerpt": boolean;
      "observation": string | null;
      "conclusion": string;
      "limitations": string | null;
      "inputs": Array<string>;
      "evidence_refs": Array<string>;
      "files": Array<{
        "name": string;
        "purpose"?: string | null;
        "artifact_ref": string;
      }>;
      "supersedes": string | null;
      "authored_node_revision": number | null;
      "basis_refs": Array<JsonValue>;
      "author": {
        "session_id": string | null;
      };
      "created_at": string;
      "subjects"?: Record<string, string>;
      "check_refs"?: Array<string>;
      "checks"?: Array<JsonValue>;
      "context_basis"?: {
        "node_revision": number;
        "sha256": string;
      };
    };
    "record"?: JsonValue;
    "review_notices"?: Array<JsonValue>;
    "review_notice_count"?: number;
    [key: string]: unknown;
  };
  "research.search": {
    "schema_version": "research-search/2";
    "records": Array<{
      "ref": string;
      "sequence": number;
      "origin": string;
      "kind": string;
      "node_id": string | null;
      "title": string;
      "excerpt": string;
      "created_at": string;
      "read": {
        "ref": string;
      };
    }>;
    "total": number;
    "next_offset": number | null;
    "index_sequence": number;
  };
  "research.create": {
    "accepted": true;
    "node": {
      "schema_version": "research-node/1";
      "id": string;
      "workspace_id": string;
      "title": string;
      "goal": string;
      "proposal": string | null;
      "plan": string | null;
      "progress": string | null;
      "status": "open" | "paused" | "closed";
      "assessment_ref": string | null;
      "source_refs": Array<string>;
      "input_refs": Array<string>;
      "revision": number;
      "created_at": string;
      "updated_at": string;
      "author": {
        "session_id": string | null;
      };
      "subjects"?: Record<string, string>;
    };
    "relations": Array<{
      "id": string;
      "source": string;
      "target": string;
      "kind": string;
      "reason": string;
      "origin": string;
      "basis_refs": Array<string>;
      "active": boolean;
      "created_at": string;
    }>;
    "read_basis": string;
    "view_error"?: string;
    "ref": string;
  };
  "research.update": {
    "accepted": true;
    "node": {
      "schema_version": "research-node/1";
      "id": string;
      "workspace_id": string;
      "title": string;
      "goal": string;
      "proposal": string | null;
      "plan": string | null;
      "progress": string | null;
      "status": "open" | "paused" | "closed";
      "assessment_ref": string | null;
      "source_refs": Array<string>;
      "input_refs": Array<string>;
      "revision": number;
      "created_at": string;
      "updated_at": string;
      "author": {
        "session_id": string | null;
      };
      "subjects"?: Record<string, string>;
    };
    "relations": Array<{
      "id": string;
      "source": string;
      "target": string;
      "kind": string;
      "reason": string;
      "origin": string;
      "basis_refs": Array<string>;
      "active": boolean;
      "created_at": string;
    }>;
    "read_basis": string;
    "view_error"?: string;
    "ref": string;
  };
  "research.result": {
    "accepted": true;
    "node": {
      "schema_version": "research-node/1";
      "id": string;
      "workspace_id": string;
      "title": string;
      "goal": string;
      "proposal": string | null;
      "plan": string | null;
      "progress": string | null;
      "status": "open" | "paused" | "closed";
      "assessment_ref": string | null;
      "source_refs": Array<string>;
      "input_refs": Array<string>;
      "revision": number;
      "created_at": string;
      "updated_at": string;
      "author": {
        "session_id": string | null;
      };
      "subjects"?: Record<string, string>;
    };
    "relations": Array<{
      "id": string;
      "source": string;
      "target": string;
      "kind": string;
      "reason": string;
      "origin": string;
      "basis_refs": Array<string>;
      "active": boolean;
      "created_at": string;
    }>;
    "read_basis": string;
    "view_error"?: string;
    "result": {
      "schema_version": "research-result/1";
      "id": string;
      "workspace_id": string;
      "node_id": string;
      "summary": string;
      "summary_is_excerpt": boolean;
      "observation": string | null;
      "conclusion": string;
      "limitations": string | null;
      "inputs": Array<string>;
      "evidence_refs": Array<string>;
      "files": Array<{
        "name": string;
        "purpose"?: string | null;
        "artifact_ref": string;
      }>;
      "supersedes": string | null;
      "authored_node_revision": number | null;
      "basis_refs": Array<JsonValue>;
      "author": {
        "session_id": string | null;
      };
      "created_at": string;
      "subjects"?: Record<string, string>;
      "check_refs"?: Array<string>;
      "checks"?: Array<JsonValue>;
      "context_basis"?: {
        "node_revision": number;
        "sha256": string;
      };
    };
    "result_saved": true;
    "assessment_selected": boolean;
    "conflict": string | null;
  };
  "research.source": {
    "source_ref": string;
    "recorded": true;
  };
  "research.observe": {
    "recorded": true;
  };
  "job.start": {
    "job_id": string;
    "platform": string;
    "submitted_at": string;
    "command": Array<string>;
    "cwd": string;
    "pid": number | null;
    "metadata": Record<string, JsonValue>;
    "workspace_id": string | null;
    "prepared_ref"?: string;
  } | {
    "job_id": string;
    "state": "unknown";
    "error": string;
  } | {
    "accepted": false;
    "code": "duplicate_execution";
    "job_id": string;
    "execution_fingerprint": string;
    "recovery": string;
  };
  "job.status": {
    "job_id": string;
    "state": "created" | "submitted" | "running" | "queued" | "held" | "succeeded" | "failed" | "timed_out" | "cancelled" | "unknown" | "collected";
    "platform": string;
    "exit_code"?: number | null;
    "started_at"?: string | null;
    "finished_at"?: string | null;
    "error"?: string | null;
    "outputs"?: Array<{
      "path": string;
      "required": boolean;
      "media_type": string | null;
      "min_bytes": number;
      "recursive": boolean;
    }>;
    "diagnostics"?: Record<string, JsonValue>;
    "execution_conflict"?: JsonValue;
  };
  "job.collect": {
    "job_id": string;
    "status": {
      "job_id": string;
      "state": "created" | "submitted" | "running" | "queued" | "held" | "succeeded" | "failed" | "timed_out" | "cancelled" | "unknown" | "collected";
      "platform": string;
      "exit_code"?: number | null;
      "started_at"?: string | null;
      "finished_at"?: string | null;
      "error"?: string | null;
      "outputs"?: Array<{
        "path": string;
        "required": boolean;
        "media_type": string | null;
        "min_bytes": number;
        "recursive": boolean;
      }>;
      "diagnostics"?: Record<string, JsonValue>;
      "execution_conflict"?: JsonValue;
    };
    "outputs": Array<{
      "path": string;
      "required": boolean;
      "exists": boolean;
      "size"?: number;
      "sha256"?: string;
    }>;
    "output_validation": {
      "complete": boolean;
      "errors": Array<{
        "path": string;
        "error": string;
      }>;
    };
    "stdout": string;
    "stderr": string;
    "artifacts": Array<{
      "artifact_id": string;
      "location": string;
      "sha256": string;
      "size_bytes": number;
      "media_type": string;
      "artifact_ref": string;
      "provenance": {
        "job_id": string | null;
        "node_id"?: string | null;
        "node_revision"?: number | null;
        "source_path"?: string;
        "name"?: string | null;
        "derivation_executed"?: boolean;
      };
    }>;
    "result_receipt": {
      "schema_version": "job-result/2";
      "receipt_id": string;
      "workspace_id": string | null;
      "job_id": string;
      "node_id": string | null;
      "node_revision": number | null;
      "execution_state": string;
      "execution_observation": {
        "schema_version": "execution-observation/1";
        "observation_id": string;
        "workspace_id": string | null;
        "job_id": string;
        "source": "job_runtime";
        "state": string | null;
        "exit_code": number | null;
        "started_at": string | null;
        "finished_at": string | null;
        "error": string | null;
      };
      "execution_observation_ref": string;
      "collection_state": "complete" | "partial";
      "artifact_refs": Array<string>;
      "output_manifest_digest": string;
      "validator_result": Record<string, JsonValue> | null;
    };
    "execution_conflict"?: JsonValue;
  };
  "job.cancel": {
    "job_id": string;
    "state": "created" | "submitted" | "running" | "queued" | "held" | "succeeded" | "failed" | "timed_out" | "cancelled" | "unknown" | "collected";
    "platform": string;
    "exit_code"?: number | null;
    "started_at"?: string | null;
    "finished_at"?: string | null;
    "error"?: string | null;
    "outputs"?: Array<{
      "path": string;
      "required": boolean;
      "media_type": string | null;
      "min_bytes": number;
      "recursive": boolean;
    }>;
    "diagnostics"?: Record<string, JsonValue>;
    "execution_conflict"?: JsonValue;
  };
  "job.probe": {
    "platform": string;
    "cwd_exists": boolean;
    "inputs_present": boolean;
    "missing_inputs": Array<string>;
    "command": Array<string>;
  } | {
    "platform": string;
    "available": boolean;
    "ssh_host": string;
    "scheduler": string;
    "remote_root": string;
    "cwd_exists": boolean;
    "inputs_present": boolean;
    "missing_inputs": Array<string>;
    "error": string | null;
  } | {
    "platform": string;
    "available": false;
    "reason": string;
  };
  "job.reconcile": {
    "job_id": string;
    "state": "created" | "submitted" | "running" | "queued" | "held" | "succeeded" | "failed" | "timed_out" | "cancelled" | "unknown" | "collected";
    "platform": string;
    "exit_code"?: number | null;
    "started_at"?: string | null;
    "finished_at"?: string | null;
    "error"?: string | null;
    "outputs"?: Array<{
      "path": string;
      "required": boolean;
      "media_type": string | null;
      "min_bytes": number;
      "recursive": boolean;
    }>;
    "diagnostics"?: Record<string, JsonValue>;
    "execution_conflict"?: JsonValue;
  };
  "job.prepare": {
    "prepared_ref": string;
    "request_id": string;
    "work_id": string;
    "request_sha256": string;
  };
  "job.resolve_prepared": {
    "job_id"?: string;
    "request_id": string;
    "command": Array<string>;
    "cwd"?: string | null;
    "inputs": Array<{
      "source": string;
      "sha256": string;
      "destination"?: string;
      [key: string]: unknown;
    }>;
    "outputs"?: Array<Record<string, unknown>>;
    "environment"?: Record<string, string> | string | null;
    "env"?: Record<string, string> | null;
    "timeout_seconds"?: number | null;
    "metadata"?: Record<string, unknown> | null;
    "workspace_id"?: string;
    "work_id": string;
    "platform"?: string;
    "execution_target"?: Record<string, unknown>;
    "session_id"?: string | null;
    "validator_id"?: string;
    "input_artifact_ids"?: Array<string>;
    "repeat"?: {
      "predecessor_job_id": string;
      "reason": string;
      "budget": string;
    };
    "prepared_ref"?: string;
    "validator_version"?: string;
    "request_file"?: string;
    "request_sha256"?: string | null;
    "node_id"?: string;
  };
  "job.monitor_assess": {
    "event_id": string;
    "event": {
      "event_id": string;
      "job_id": string;
      "node_id": string | null;
      "node_revision": number | null;
      "workspace_id": string;
      "session_id": string;
      "state": string;
      [key: string]: unknown;
    };
    "obsolete": boolean;
    "admitted": boolean;
    "reason": "already_delivered" | "attention_required" | "paused";
    "delivery_token": string;
  };
  "artifact.register": {
    "artifact_id": string;
    "location": string;
    "sha256": string;
    "size_bytes": number;
    "media_type": string;
    "artifact_ref": string;
    "provenance": {
      "job_id": string | null;
      "node_id"?: string | null;
      "node_revision"?: number | null;
      "source_path"?: string;
      "name"?: string | null;
      "derivation_executed"?: boolean;
    };
  };
  "artifact.create": {
    "artifact_id": string;
    "location": string;
    "sha256": string;
    "size_bytes": number;
    "media_type": string;
    "artifact_ref": string;
    "provenance": {
      "job_id": string | null;
      "node_id"?: string | null;
      "node_revision"?: number | null;
      "source_path"?: string;
      "name"?: string | null;
      "derivation_executed"?: boolean;
    };
  };
  "artifact.read": {
    "artifact_id": string;
    "location": string;
    "sha256": string;
    "size_bytes": number;
    "media_type": string;
    "artifact_ref": string;
    "content": string;
    "next_offset": number | null;
  };
}

export type CommandId = keyof CommandParameters;
export interface CommandInvocation {
  readonly command: CommandId;
  readonly params: Readonly<Record<string, unknown>>;
}
export interface CommandTransportInvocation extends CommandInvocation {
  readonly root: string;
  readonly signal?: AbortSignal;
}
export const COMMAND_DEFINITIONS: Readonly<Record<CommandId, {
  readonly id: CommandId;
  readonly domain: "research" | "runtime";
  readonly effect?: "read" | "write";
  readonly required: readonly string[];
  readonly allowed: readonly string[];
  readonly schema: Readonly<Record<string, unknown>>;
  readonly result: Readonly<Record<string, unknown>>;
}>>;
export const COMMAND_IDS: readonly CommandId[];
export const SLASH_COMMAND_DEFINITIONS: Readonly<Record<string, {
  readonly name: string;
  readonly description: string;
  readonly usage: string;
  readonly completions: readonly string[];
}>>;
export const SLASH_COMMAND_NAMES: readonly string[];
export function createCommandService(transport: {
  execute(invocation: CommandTransportInvocation): Promise<unknown>;
}): {
  execute<C extends CommandId>(command: C, root: string, params?: Record<string, unknown>, signal?: AbortSignal): Promise<CommandResults[C]>;
};
export function validateCommandInvocation(command: string, params?: Record<string, unknown>): CommandInvocation;
export function commandArguments(command: string, params?: Record<string, unknown>): string[];
export function parseSlashCommand(name: string, input?: string): CommandInvocation | {
  readonly command: "client.sys-prompt" | "client.resume" | "client.quit" | "client.usage" | "client.monitor";
  readonly params: Readonly<Record<string, unknown>>;
};
export function slashCompletions(name: string, prefix?: string): Array<{ value: string; label: string }> | null;
