// Generated by tools/generate_contracts.py. Do not edit independently.
export interface ToolParameters {
  state: {
    "root"?: string;
    "ref"?: string;
    "field"?: "goal" | "title" | "proposal" | "plan" | "progress" | "status" | "assessment_ref" | "relations";
    "offset"?: number;
    "limit"?: number;
  };
  search: {
    "root"?: string;
    "query"?: string;
    "node_id"?: string;
    "type"?: "node" | "result" | "record";
    "origin"?: "user" | "runtime" | "agent";
    "after_sequence"?: number;
    "offset"?: number;
    "limit"?: number;
  };
  create: {
    "root"?: string;
    "goal": string;
    "title"?: string;
    "proposal"?: string;
    "plan"?: string;
    "source_refs"?: Array<string>;
    "input_refs"?: Array<string>;
    "relations"?: Array<{
      "kind": "part_of" | "requires" | "alternative_to";
      "target": string;
      "reason"?: string;
    }>;
    "subjects"?: Record<string, string>;
  };
  update: {
    "root"?: string;
    "node_id": string;
    "note": string;
    "proposal"?: string;
    "plan"?: string;
    "progress"?: string;
    "status"?: "open" | "paused" | "closed";
    "add_relations"?: Array<{
      "kind": "part_of" | "requires" | "alternative_to";
      "target": string;
      "reason"?: string;
    }>;
    "remove_relations"?: Array<string>;
    "assessment_ref"?: string;
    "subjects"?: Record<string, string>;
  };
  result: {
    "root"?: string;
    "node_id": string;
    "conclusion": string;
    "summary"?: string;
    "observation"?: string;
    "limitations"?: string;
    "inputs"?: Array<string>;
    "evidence_refs"?: Array<string>;
    "files"?: Array<{
      "name": string;
      "purpose"?: string;
      "artifact_ref": string;
    }>;
    "supersedes"?: string;
    "as_assessment"?: boolean;
    "subjects"?: Record<string, string>;
    "check_refs"?: Array<string>;
    "progress"?: string;
  };
  jobStart: {
    "node_id": string;
    "request_id"?: string;
    "validator_id"?: string;
    "validator_version"?: string;
    "input_artifact_ids"?: Array<string>;
    "work_id"?: string;
    "repeat"?: {
      "predecessor_job_id": string;
      "reason": string;
      "budget": string;
    };
    "request_file"?: string;
    "prepared_ref"?: string;
    "request_sha256"?: string;
    "metadata"?: Record<string, unknown>;
    "command"?: Array<string>;
    "cwd"?: string;
    "environment"?: Record<string, string>;
    "inputs"?: Array<string | {
      "source": string;
      "sha256"?: string;
      "destination": string;
    }>;
    "outputs"?: Array<{
      "path": string;
      "required"?: boolean;
      "min_bytes"?: number;
      "recursive"?: boolean;
      "media_type"?: string;
    }>;
    "timeout_seconds"?: number;
    "platform"?: string;
    "root"?: string;
  };
  jobStatus: {
    "job_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  jobCollect: {
    "job_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  jobCancel: {
    "job_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  jobProbe: {
    "platform"?: string;
    "root"?: string;
  };
  jobReconcile: {
    "job_id"?: string;
    "event_id"?: string;
    "root"?: string;
  };
  artifactRegister: {
    "path": string;
    "job_id"?: string;
    "media_type"?: string;
    "root"?: string;
  };
  artifactCreate: {
    "content": string;
    "name": string;
    "media_type"?: string;
    "root"?: string;
  };
  artifactRead: {
    "artifact_id"?: string;
    "artifact_ref"?: string;
    "offset"?: number;
    "limit"?: number;
    "root"?: string;
  };
  taskBegin: {
    "title": string;
    "objective": string;
    "source_submission_ids": Array<string>;
    "criteria": Array<{
      "id": string;
      "description": string;
    }>;
  };
  taskRead: Record<string, never>;
  taskUpdate: {
    "expected_revision": number;
    "action": "refine" | "progress" | "wait" | "block" | "propose_completion" | "set_research";
    "reason"?: string;
    "objective"?: string;
    "criteria"?: Array<{
      "id": string;
      "description": string;
    }>;
    "source_submission_ids"?: Array<string>;
    "evidence_refs"?: Array<string>;
    "wait"?: {
      "job_ids": Array<string>;
      "mode": "all" | "any";
    };
    "completion"?: Array<{
      "criterion_id": string;
      "evidence_refs": Array<string>;
    }>;
    "research"?: {
      "entry_node_ids": Array<string>;
      "focus_node_ids": Array<string>;
    };
  };
}
